pagopa/interop-be-monorepo

open-api/catalog-service-spec.yml
src/model/generated/api.ts

Catalog Service complete API spec and updated models in `api.ts`

Add complete API specs and model generation

---

packages/catalog-process/src/utilities/config.ts
packages/catalog-process/src/utilities/fileManager.ts
packages/commons/src/config/index.ts

This PR applies discriminant type unions for required and optional configurations provided by env variables.

Use Zod parser and inferred type for env configurations

---

packages/catalog-process/kubernetes/dev/deployment.yaml
packages/event-consumer/kubernetes/dev/deployment.yaml

Fix wrong `key` field in K8s deployment.yaml files

Fix deployment dev

---

.github/workflows/dev.yml
packages/catalog-consumer/Dockerfile

Update CI with new paths for `catolog-consumer`

Update dev CI with new paths for catalog-consumer

---

packages/catalog-consumer/kubernetes/dev/configmap.yaml
packages/catalog-consumer/kubernetes/dev/deployment.yaml
packages/catalog-consumer/kubernetes/dev/serviceAccount.yaml

This PR align catalog-consumer for naming convention

Update CI with new naming convention

---

kubernetes/common/dev/configmap.yaml
packages/catalog-consumer/kubernetes/dev/deployment.yaml
packages/catalog-process/kubernetes/dev/deployment.yaml

Add those configurations as env variables 
- SKIP_JWT_VERIFICATION : if true skip JWT signature verification, otherwise WELL_KNOWN_URLS is mandatory
- WELL_KNOWN_URLS : well know hosts array using for JWT signature validation ("," array separator); optional if SKIP_JWT_VERIFICATION is true
`dev` environment the skip JWT signature verification

Update dev config maps

---

packages/catalog-consumer/src/model/converter.ts
packages/catalog-process/open-api/catalog-service-spec.yml
packages/catalog-process/src/model/domain/apiConverter.ts
packages/catalog-process/src/repositories/toEvent.ts
packages/catalog-process/src/services/catalogService.ts
packages/catalog-process/test/catalogService.test.ts
packages/models/src/eservice.ts

fix: https://pagopa.atlassian.net/browse/IMN-2 (already fixed in the previous implementation)
fix: https://pagopa.atlassian.net/browse/IMN-14

IMN-14 - Attributes refactor

---

packages/agreement-process/open-api/agreement-service-spec.yml
packages/agreement-process/src/app.ts
packages/agreement-process/src/model/types.ts
packages/agreement-process/src/routers/AgreementRouter.ts
packages/models/src/errors.ts

This PR defines the open API specs for the agreement service and bootstraps the main agreement router.

IMN 29 - Porting Agreement openapi

---

packages/catalog-process/kubernetes/dev/deployment.yaml

Fix wrong config map reference during dev deployment for catalog-process service

Fix configmap for catalog process service

---

packages/agreement-consumer/package.json
packages/agreement-consumer/src/agreementConsumerService.ts
packages/agreement-process/package.json
packages/agreement-process/src/services/readModelService.ts
packages/catalog-consumer/package.json
packages/catalog-consumer/src/consumerService.ts
packages/catalog-process/src/services/readModelService.ts
packages/commons/package.json
packages/commons/src/index.ts
packages/commons/src/repositories/ReadModelRepository.ts
pnpm-lock.yaml

IMN 75 -  BKE ReadModel Client

---

packages/agreement-consumer/src/model/converter.ts
packages/agreement-process/src/model/domain/apiConverter.ts
packages/agreement-process/src/model/domain/toEvent.ts
packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/services/readModelService.ts
packages/agreement-process/src/services/validators.ts
packages/catalog-process/src/model/domain/apiConverter.ts
packages/catalog-process/src/model/domain/models.ts
packages/catalog-process/src/services/readModelService.ts
packages/commons/src/repositories/ReadModelRepository.ts
packages/models/src/agreement/agreement.ts

This PR rename agreement models removing `persistent` prefix
Close [IMN-79](https://pagopa.atlassian.net/browse/IMN-79?atlOrigin=eyJpIjoiN2NkZDgzYTJhZGFhNGU1ZGJhN2IzNjkzYzRlMjMzNDAiLCJwIjoiaiJ9)
[IMN-79]: https://pagopa.atlassian.net/browse/IMN-79?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-79 renaming agreement persistent models

---

packages/catalog-consumer/Dockerfile

This PR fix CI build task, add kafka-iam-auth folder to docker image.

Fix Dev CI add kafka-iam-auth to Docker image

---

packages/agreement-consumer/src/agreementConsumerService.ts
packages/agreement-consumer/src/model/models.ts
packages/agreement-process/src/model/domain/toEvent.ts
packages/agreement-process/src/model/types.ts
packages/agreement-process/src/routers/AgreementRouter.ts
packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/services/validators.ts
packages/models/src/agreement/agreementEvents.ts

This PR adds the logic to update an `Agreement`

IMN 45 - Agreement update

---

.eslintrc.cjs
.github/workflows/pr.yml
packages/catalog-process/src/services/catalogService.ts

Resolve [IMN-152](https://pagopa.atlassian.net/browse/IMN-152) for catalog-process publishDescriptor
Plus Fix CI linter
[IMN-152]: https://pagopa.atlassian.net/browse/IMN-152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN 152 - Fix event version

---

packages/agreement-process/src/routers/AgreementRouter.ts
packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/services/readmodel/agreementQuery.ts
packages/agreement-process/src/services/readmodel/readModelService.ts

Closes [IMN-41](https://pagopa.atlassian.net/browse/IMN-41)
[IMN-41]: https://pagopa.atlassian.net/browse/IMN-41?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
This PR implements GET /producers.
Tested manually.
I have two agreements with two different producers, here's the query results with different params to test the name search and all edge cases.

IMN-41 - GET Agreement producers

---

packages/catalog-process/kubernetes/dev/deployment.yaml

fix: catalog process K8s ports

---

packages/agreement-process/open-api/agreement-service-spec.yml
packages/agreement-process/src/routers/AgreementRouter.ts
packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/utilities/errorMappers.ts
packages/models/src/agreement/agreement.ts

Close [IMN-31](https://pagopa.atlassian.net/browse/IMN-47)
This PR implements agreement cloning API.
[IMN-31]: https://pagopa.atlassian.net/browse/IMN-31?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN 47 - Post Agreement Clone

---

packages/agreement-process/src/model/domain/models.ts
packages/agreement-process/src/routers/AgreementRouter.ts
packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/services/readmodel/agreementQuery.ts
packages/agreement-process/src/services/readmodel/readModelService.ts

Close [IMN-49](https://pagopa.atlassian.net/browse/IMN-49)
[IMN-49]: https://pagopa.atlassian.net/browse/IMN-49?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN 49 - Get agreement filter EServices

---

packages/agreement-process/open-api/agreement-service-spec.yml
packages/agreement-process/src/model/domain/validators.ts
packages/agreement-process/src/routers/AgreementRouter.ts
packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/services/agreementSuspensionProcessor.ts
packages/agreement-process/src/utilities/errorMappers.ts
packages/models/src/agreement/agreement.ts

Close [IMN-37](https://pagopa.atlassian.net/browse/IMN-37)
This PR implements API POST /agreements/:agreementId/reject
Tested locally as follows:
```
{
_id: ObjectId('659bca9bbd10d1dd69af9caa'),
data: {
id: '6f19d313-c394-4622-9a96-894dccae8464',
eserviceId: '29fcdf9d-7bca-4b88-87e7-ac3d886c7bd5',
descriptorId: '70337b5d-2649-4052-a552-b28bd0b1f1ab',
producerId: '4D55696F-16C0-4968-854B-2B166397FC30',
consumerId: '4D55696F-16C0-4968-854B-2B166397FC30',
state: 'Pending',
verifiedAttributes: [],
createdAt: ISODate('2024-01-08T10:12:42.748Z'),
certifiedAttributes: [],
declaredAttributes: [],
consumerDocuments: [],
stamps: {},
updatedAt: ISODate('1970-01-01T00:00:00.000Z')
},
metadata: {
version: 0
}
}
```
```
{
_id: ObjectId('659bca9bbd10d1dd69af9caa'),
data: {
id: …
```

IMN 37 - Post Agreement Reject

---

packages/agreement-process/open-api/agreement-service-spec.yml
packages/agreement-process/src/routers/AgreementRouter.ts
packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/utilities/errorMappers.ts

Close [IMN-38](https://pagopa.atlassian.net/browse/IMN-38?atlOrigin=eyJpIjoiZjM2YTdiY2ZjZWRjNGU2Mzk5ZjliY2JjMzBkYjJiZWYiLCJwIjoiaiJ9)
Implements agreement `archive` API, set agreement state to _ARCHIVE_.
✅  Local E2E test
[IMN-38]: https://pagopa.atlassian.net/browse/IMN-38?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-38 post agreement archive

---

packages/attribute-registry-process/src/model/domain/errors.ts
packages/attribute-registry-process/src/routers/AttributeRouter.ts
packages/attribute-registry-process/src/services/attributeRegistryService.ts
packages/attribute-registry-process/src/services/readModelService.ts

This PR introduces the branded types for the `attribute-registry` package

IMN 166 - Refactor branded type 4

---

packages/agreement-process/src/model/domain/models.ts
packages/agreement-process/src/model/domain/validators.ts
packages/agreement-process/src/services/agreementActivationProcessor.ts
packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/services/agreementSuspensionProcessor.ts
packages/models/src/agreement/agreement.ts

Add minor fixes on attribute validators, the method `attributesSatisfied` doesn't filter revoked attributes properly.
✅  All test successed.

Minor fix on validators

---

packages/commons/src/config/fileManagerConfig.ts

Code reference [here](https://github.com/pagopa/interop-be-monorepo/blob/main/packages/commons/src/config/commonConfig.ts#L4)

IMN-270: make S3_CUSTOM_SERVER env var optional

---

packages/models/src/errors.ts

Improve [IMN-150](https://pagopa.atlassian.net/browse/IMN-150)
[IMN-150]: https://pagopa.atlassian.net/browse/IMN-150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN 150 - Improve generic error log

---

packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/services/pdfGenerator.ts
packages/catalog-process/package.json
packages/catalog-process/src/services/catalogService.ts
packages/catalog-process/src/utilities/date.ts
packages/catalog-process/test/catalogService.integration.test.ts
pnpm-lock.yaml

Closes [IMN-262](https://pagopa.atlassian.net/browse/IMN-262)
This PR:
* Fixes the Clone Descriptor implementation, where filemanager was not called correctly
* Adds tests for all calls involving filemanager, actually testing the filemanager integration
* **NOTE: there is another test that must be added when https://github.com/pagopa/interop-be-monorepo/pull/204 is merged, it will be done in a further PR** (tracked here https://pagopa.atlassian.net/browse/IMN-275)
Covering file manager integration in all tests that involve file manager calls - new automated tests work ✅
[IMN-262]: https://pagopa.atlassian.net/browse/IMN-262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN 262 - implement & test all file manager usages in catalog

---

packages/catalog-process/test/catalogService.integration.test.ts

Closes [IMN-275](https://pagopa.atlassian.net/browse/IMN-275)
The two tests succeed ✅
[IMN-275]: https://pagopa.atlassian.net/browse/IMN-275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-275 - Add file manager integration tests for interface delete on technology update

---

packages/authorization-updater/.env
packages/authorization-updater/kubernetes/configmap.yaml
packages/authorization-updater/kubernetes/deployment.yaml

This Pr add missing env variable required for Authorization Updater service

Add missing env config for Authorization Updater service

---

packages/kafka-iam-auth/src/index.ts

Closes [IMN-302](https://pagopa.atlassian.net/browse/IMN-302)
I think that some of this log message should remain of type `info`
[IMN-302]: https://pagopa.atlassian.net/browse/IMN-302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN 302 - Riduzione log Kafka Iam service

---

packages/catalog-process/open-api/catalog-service-spec.yml
packages/catalog-process/src/model/domain/apiConverter.ts
packages/catalog-process/src/routers/EServiceRouter.ts
packages/catalog-process/src/services/catalogService.ts

This pull request is for fixing a bug due to the difference in the response payload respect to the Scala implementation. The updateDocument endpoint was returing 200 with no object, whereas it should return the updated document.

IMN-335 Fix returned payload in updateDocument in catalog-process

---

packages/kafka-iam-auth/README.md

Closes [IMN-303](https://pagopa.atlassian.net/browse/IMN-303)
[IMN-303]: https://pagopa.atlassian.net/browse/IMN-303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN 303 - Consumer disconnection

---

packages/models/src/tenant/tenant.ts

This pull request is for renaming `ContactEmail` in `CONTACT_EMAIL` to make it coherent with the Scala implementation.

IMN-362 Fix tenantMailKind for tenants

---

docker/docker-compose.yml
docker/elasticmq.local.conf
packages/agreement-process/aws.config.local
packages/catalog-process/aws.config.local
packages/commons-test/aws.config.local
packages/commons-test/elasticmq.custom.conf
packages/commons-test/elasticmq.local.conf
packages/commons-test/src/containerTestUtils.ts
packages/commons-test/test/queueManager.integration.test.ts
packages/commons/package.json
packages/commons/src/index.ts
packages/commons/src/queue-manager/index.ts
packages/commons/src/queue-manager/models.ts
packages/commons/src/queue-manager/queueManager.ts
packages/commons/src/queue-manager/queueManagerErrors.ts
pnpm-lock.yaml

Closes [IMN-344](https://pagopa.atlassian.net/browse/IMN-344)
This PR implements an SQS queue writer, based on the one from the Scala codebase: [see here](https://github.com/pagopa/interop-commons/blob/1f4fa7b28b005e2af518c4abe3139daee8ac7fee/queue-manager/src/main/scala/it/pagopa/interop/commons/queue/impl/SQSWriter.scala#L25)
It will then be used to send notification messages to the existing SQS queue, as done by the `catalog-management` service in the Scala codebase: [see here](https://github.com/pagopa/interop-be-catalog-management/blob/58f22eef590b2bc267cb7fbf8777237d0eae3b23/src/main/scala/it/pagopa/interop/catalogmanagement/model/persistence/projection/CatalogNotificationProjection.scala#L27) (tracked as a further task in Jira)
[IMN-344]: …

 IMN-344 - Implementing SQS queue manager

---

packages/commons/src/auth/authenticationMiddleware.ts

This pull request is for returning 403 instead of 401 in case of `unauthorizedError`.

IMN-372 Change returned status code in case of unauthorizedError

---

packages/commons/src/auth/authorizationMiddleware.ts

This pull request is for returning 403 instead of 401 in case of `unauthorizedError.`

IMN-372 Fix unauthorized part2

---

packages/commons/src/auth/authenticationMiddleware.ts

This pull request is for reverting a previous fix (#297) that wasn't necessary. The only needed fix is #298.

IMN-372 Revert wrong fix

---

packages/models/src/eservice/eserviceEvents.ts

Closes [IMN-377](https://pagopa.atlassian.net/browse/IMN-377)
[IMN-377]: https://pagopa.atlassian.net/browse/IMN-377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN 377 - Fix EServiceDescriptorQuotasUpdated payload

---

packages/catalog-process/src/utilities/errorMappers.ts

This pull request is for changing the returned status code when trying to delete an eservice with non-draft descriptors.

IMN-376 Fix deleteEServiceErrorMapper in catalog-process

---

packages/authorization-updater/src/index.ts
packages/commons/src/logging/loggerMiddleware.ts

This PR fix the Auth updater service behaviour, now ignore useless catalog event properly.

Fix auth updater handling invalid msg

---

packages/agreement-process/src/model/domain/validators.ts
packages/agreement-process/src/services/agreementActivationProcessor.ts
packages/agreement-process/src/services/agreementCreationProcessor.ts
packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/services/agreementSubmissionProcessor.ts
packages/agreement-process/src/services/agreementSuspensionProcessor.ts
packages/agreement-process/src/services/pdfGenerator.ts
packages/agreement-process/src/services/readmodel/attributeQuery.ts
packages/agreement-process/src/services/readmodel/eserviceQuery.ts
packages/agreement-process/src/services/readmodel/readModelService.ts
packages/agreement-process/src/services/readmodel/tenantQuery.ts

Closes [IMN-353](https://pagopa.atlassian.net/browse/IMN-353)
Tests pass ✅
[IMN-353]: https://pagopa.atlassian.net/browse/IMN-353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-353 - Remove metadata from non-Agreement queries in agreement-process

---

.github/workflows/renovate.yml
renovate.json

Closes [IMN-304](https://pagopa.atlassian.net/browse/IMN-304)
[IMN-304]: https://pagopa.atlassian.net/browse/IMN-304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-304 - Adding renovate GH action & configuration

---

renovate.json

Needed to run Renovate and close: [IMN-411](https://pagopa.atlassian.net/browse/IMN-411)
[IMN-411]: https://pagopa.atlassian.net/browse/IMN-411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-411 - Adding missing Renovate options

---

packages/agreement-process/Dockerfile
packages/agreement-readmodel-writer/Dockerfile
packages/attribute-registry-process/Dockerfile
packages/attribute-registry-readmodel-writer/Dockerfile
packages/authorization-updater/Dockerfile
packages/catalog-process/Dockerfile
packages/catalog-readmodel-writer/Dockerfile
packages/notifier-seeder/DockerFile
packages/tenant-process/Dockerfile
packages/tenant-readmodel-writer/Dockerfile

Add missing folder during  copy in DockerFile

Fix docker img multipstep build

---

packages/agreement-process/src/routers/AgreementRouter.ts
packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/utilities/errorMappers.ts
packages/agreement-process/test/agreementService.integration.test.ts

[ To be merged after #322 ]
Closes [IMN-217](https://pagopa.atlassian.net/browse/IMN-217)
---
---
[IMN-217]: https://pagopa.atlassian.net/browse/IMN-217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-217 - Adding tests for getAgreementById

---

packages/catalog-process/test/catalogService.integration.test.ts

See discussion here: https://github.com/pagopa/interop-be-monorepo/pull/347#issuecomment-2045126521

Removing readmodel service tests section in catalog

---

packages/authorization-updater/open-api/authorization-management.spec.yaml
packages/catalog-process/open-api/catalog-service-spec.yml
packages/purpose-process/open-api/purpose-service-spec.yml

With this pull request, `application/problem+json` is replaced with `application/json` to ensure the generator can produce an accurate model. 
This change is necessary as `problem+json` isn't supported.
The files have been prettified so there's a lot of rumor in the changes, I suggest to use `Hide whitespace` which helps a bit.

IMN-433: fixed openApis

---

packages/agreement-readmodel-writer/src/index.ts
packages/attribute-registry-readmodel-writer/src/index.ts
packages/authorization-updater/src/index.ts
packages/catalog-readmodel-writer/src/index.ts
packages/commons/src/context/context.ts
packages/notifier-seeder/src/index.ts
packages/purpose-readmodel-writer/src/index.ts
packages/tenant-readmodel-writer/src/index.ts

IMN 486 - Fix await run with context

---

packages/commons/src/context/context.ts
packages/commons/src/logging/index.ts

Fix a logger-related bug introduced with https://github.com/pagopa/interop-be-monorepo/pull/423

IMN 473 - Fix logger

---

packages/agreement-process/src/services/agreementService.ts
packages/commons/src/repositories/EventRepository.ts

Closes [IMN 507](https://pagopa.atlassian.net/browse/IMN-507)
Event creation still works

IMN 507 - Create multiple events in the same transaction

---

packages/kafka-iam-auth/src/index.ts

Closes [IMN-494](https://pagopa.atlassian.net/browse/IMN-494)
[IMN-494]: https://pagopa.atlassian.net/browse/IMN-494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN 494 - Add consumer starting log

---

packages/kafka-iam-auth/package.json
packages/kafka-iam-auth/src/index.ts
pnpm-lock.yaml

Rebalance logs are generated by `kafkajs` so the only way to reduce the level of these kinds of messages is to use a custom logger that checks the log content and if it's a rebalance log changes the final log level

IMN 495 - reduce kafka rebalance log level

---

.npmrc
packages/agreement-process/package.json
packages/agreement-readmodel-writer/package.json
packages/commons-test/package.json
packages/commons/package.json
packages/eservice-descriptors-archiver/package.json
pnpm-lock.yaml

Revert "IMN-504 - pnpm stricter peer dependencies (#539)"

---

packages/attribute-registry-process/test/attributeRegistryService.integration.test.ts

Closes [IMN-592](https://pagopa.atlassian.net/browse/IMN-592)
[IMN-592]: https://pagopa.atlassian.net/browse/IMN-592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN 592 - Add attribute registry return value test

---

packages/agreement-process/test/activateAgreement.test.ts

Closes [IMN-627 ](https://pagopa.atlassian.net/browse/IMN-627)

IMN-627 - Fixing activate agreement test flakyness

---

packages/agreement-email-sender/src/index.ts
packages/agreement-email-sender/src/services/agreementEmailSenderService.ts
packages/agreement-email-sender/test/agreementEmailSender.integration.test.ts

EmailSender sent email service commit message on kafka if throws error.

Fix email sender commit kafka during error

---

packages/purpose-process/src/services/purposeService.ts
packages/purpose-process/src/services/validators.ts
packages/purpose-process/test/createPurposeVersion.test.ts

This pull request is for fixing a bug during the update of the `dailyCalls` of a purpose. When updating those, the previous value should be excluded from the sum to evaluate whether the threshold is exceeded or not.

IMN-443 Fix purpose daily calls

---

packages/client-readmodel-writer/kubernetes/dev/deployment.yaml

This pull request is for fixing a problem that might arise from a bug in the `deployment` file.

IMN-575 Other fix on deploy of auth packages

---

packages/agreement-email-sender/Dockerfile
packages/authorization-process/package.json

Fixing build & removing unneeded dep after api-clients migration

---

packages/purpose-process/src/model/domain/apiConverter.ts

This pull request is for fixing a bug due to not returning the `rejectionReason`. We need this info in frontend.

PIN-5174 Add rejectionReason in purposeVersion converter

---

packages/authorization-process/src/model/domain/toEvent.ts
packages/authorization-process/src/routers/AuthorizationRouter.ts
packages/authorization-process/src/services/authorizationService.ts
packages/authorization-process/src/utilities/errorMappers.ts
packages/authorization-process/test/removeProducerKeychainEService.test.ts

Closes [PIN-5189](https://pagopa.atlassian.net/browse/PIN-5189)
Merge after #875
Added business logic for DELETE /producerKeychains/{producerKeychainId}/eservices/{eserviceId}
[PIN-5189]: https://pagopa.atlassian.net/browse/PIN-5189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN-5189 - DELETE /producerKeychains/{producerKeychainId}/eservices/{eserviceId}

---

packages/bff/src/app.ts
packages/bff/src/routers/authorizationRouter.ts
packages/bff/src/services/authorizationService.ts
packages/bff/src/utilities/errorMappers.ts
packages/commons/src/rate-limiter/rateLimiterUtils.ts

Based on #900 
Closes [IMN-774](https://pagopa.atlassian.net/browse/IMN-774)
[IMN-774]: https://pagopa.atlassian.net/browse/IMN-774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-774 - BFF - rate limit getSessionToken

---

packages/bff/src/routers/tenantRouter.ts
packages/bff/src/services/tenantService.ts

Based on #933 
3rd part of [IMN-607](https://pagopa.atlassian.net/browse/IMN-607)
This PR implements the following BFF tenant methods:
- Verify Verified Attribute
- Update Verified Aattribute
- Add Tenant Email
- Delete Tenant Email
[IMN-607]: https://pagopa.atlassian.net/browse/IMN-607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-607 - BFF Tenant router - Pt3

---

packages/api-gateway/.env
packages/api-gateway/src/api/attributesApiConverter.ts
packages/api-gateway/src/api/tenantApiConverter.ts
packages/api-gateway/src/clients/clientsProvider.ts
packages/api-gateway/src/config/config.ts
packages/api-gateway/src/routers/apiGatewayRouter.ts
packages/api-gateway/src/services/agreementService.ts
packages/api-gateway/src/utilities/arrays.ts
packages/bff/src/services/agreementService.ts
packages/bff/src/services/purposeService.ts
packages/commons/src/utils/arrays.ts
packages/tenant-process/.env

Based on #903 
Closes [IMN-744](https://pagopa.atlassian.net/browse/IMN-744)
This error  "bubbles up" from the agreement process API call response:
[IMN-744]: https://pagopa.atlassian.net/browse/IMN-744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-744 - API Gateway - GET Agreement Attributes

---

packages/bff/src/routers/catalogRouter.ts
packages/bff/src/services/catalogService.ts

See PR comment: https://github.com/pagopa/interop-be-monorepo/pull/979#discussion_r1763448906

Fixing descriptorId parameter bug in catalog service BFF

---

packages/api-gateway/src/models/errors.ts
packages/api-gateway/src/routers/apiGatewayRouter.ts
packages/api-gateway/src/services/agreementService.ts
packages/api-gateway/src/services/purposeService.ts
packages/api-gateway/src/services/validators.ts
packages/api-gateway/src/utilities/errorMappers.ts

Based on #906 
Closes [IMN-765](https://pagopa.atlassian.net/browse/IMN-765)
[IMN-765]: https://pagopa.atlassian.net/browse/IMN-765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-765 - API Gateway - GET Purpose Agreement

---

packages/agreement-process/src/services/readModelService.ts
packages/attribute-registry-process/src/services/readModelService.ts
packages/authorization-process/src/services/readModelService.ts
packages/catalog-process/src/services/readModelService.ts
packages/commons/src/repositories/ReadModelRepository.ts
packages/purpose-process/src/services/readModelService.ts
packages/tenant-process/src/services/readModelService.ts

Adding allow disk use in all Mongo aggregations

---

packages/backend-for-frontend/src/services/agreementService.ts

```
f4503c-9929-4bdf-b5b6-1d933dc0a322] - title: Unexpected error - detail: Unexpected erro │
│ f4503c-9929-4bdf-b5b6-1d933dc0a322]   {                                                 │
│ f4503c-9929-4bdf-b5b6-1d933dc0a322]     "code": "unrecognized_keys",                    │
│ f4503c-9929-4bdf-b5b6-1d933dc0a322]     "keys": [                                       │
│ f4503c-9929-4bdf-b5b6-1d933dc0a322]       "voucherLifespan",                            │
│ f4503c-9929-4bdf-b5b6-1d933dc0a322]       "dailyCallsPerConsumer",                      │
│ f4503c-9929-4bdf-b5b6-1d933dc0a322]       "dailyCallsTotal",                            │
│ f4503c-9929-4bdf-b5b6-1d933dc0a322]       "interface",                                  │
│ f4503c-9929-4bdf-b5b6-1d933dc0a322]       "docs", …
```

Fix bug - Use toCompactDescriptor

---

packages/backend-for-frontend/src/utilities/fileUtils.ts

Close [IMN-836](https://pagopa.atlassian.net/browse/IMN-836)
Document's path used during creation a zip file access to s3 document file with wrong key 
[IMN-836]: https://pagopa.atlassian.net/browse/IMN-836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-836 - Fix file Utils zip file document fetching 

---

packages/backend-for-frontend/src/routers/catalogRouter.ts
packages/backend-for-frontend/src/utilities/errorMappers.ts
packages/backend-for-frontend/src/utilities/eserviceDocumentUtils.ts

Closes [IMN-849](https://pagopa.atlassian.net/browse/IMN-849)
[IMN-849]: https://pagopa.atlassian.net/browse/IMN-849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-849: fix various BFF mappers

---

packages/authorization-process/src/utilities/errorMappers.ts
packages/backend-for-frontend/src/routers/clientRouter.ts

Closes [IMN-874](https://pagopa.atlassian.net/browse/IMN-874)
[IMN-874]: https://pagopa.atlassian.net/browse/IMN-874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-874: added error to createKeys and createProducerKeychainKey mapper

---

docker/event-store-init.sql
packages/commons-test/src/eventStoreTestUtils.ts
packages/commons-test/src/setupTestContainersVitest.ts
packages/commons-test/src/testUtils.ts
packages/commons/src/repositories/ReadModelRepository.ts
packages/models/proto/v2/delegation/delegation.proto
packages/models/proto/v2/delegation/events.proto
packages/models/src/brandedIds.ts
packages/models/src/delegation/delegation.ts
packages/models/src/delegation/delegationEvents.ts
packages/models/src/index.ts

Closes [PIN-5363](https://pagopa.atlassian.net/browse/PIN-5363?atlOrigin=eyJpIjoiMDYyNTI5MzcyYzBlNGRhNmJhOTQ1NzI4YmI1YWQyODMiLCJwIjoiaiJ9)
This PR introduces delegation domain model and related events definitions.
[PIN-5363]: https://pagopa.atlassian.net/browse/PIN-5363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Pin 5363 delegation models

---

packages/api-clients/open-api/delegationApi.yml

This PR adds the open api spec for delegation process.

PIN-5394 Add delegation process api spec

---

packages/backend-for-frontend/src/services/toolService.ts

Closes [IMN-888](https://pagopa.atlassian.net/browse/IMN-888)
[IMN-888]: https://pagopa.atlassian.net/browse/IMN-888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-888 - /tools/validateTokenGeneration fixes after testing in dev

---

packages/client-assertion-validation/src/validation.ts
packages/client-assertion-validation/test/keyImport.test.ts
packages/client-assertion-validation/test/utils.ts
packages/commons/src/auth/jwk.ts

IMN-889 - Using crypto functions instead of jose functions to import keys

---

packages/backend-for-frontend/src/services/selfcareService.ts

This bug has been introduced by this [PR](https://github.com/pagopa/interop-be-monorepo/pull/1122/files#diff-b7632f3bd27f5c01996b8accc6fa205d3046f30e7d846a533e9eaeeb60c19a06R115-R117)

IMN-908 Add header, including authorization

---

packages/delegation-process/package.json
pnpm-lock.yaml

Closes  [PIN-5553](https://pagopa.atlassian.net/browse/PIN-5553),
This PR remove dependancies `uuid` and `@types/uuid` from delegation process package.json
[PIN-5553]: https://pagopa.atlassian.net/browse/PIN-5553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove uuid and @types/uuid from dependancies

---

collections/bff/delegation/Approve Delegation.bru
collections/bff/delegation/Create Delegation.bru
collections/bff/delegation/Get Delegation ById.bru
collections/bff/delegation/Get Delegations.bru
collections/bff/delegation/Reject Delegation.bru
collections/bff/delegation/Revoke Delegation.bru
packages/api-clients/open-api/bffApi.yml
packages/api-clients/template-bff.hbs
packages/api-clients/template.hbs
packages/backend-for-frontend/.env
packages/backend-for-frontend/src/api/delegationApiConverter.ts
packages/backend-for-frontend/src/clients/clientsProvider.ts
packages/backend-for-frontend/src/model/errors.ts
packages/backend-for-frontend/src/routers/delegationRouter.ts
packages/backend-for-frontend/src/routers/producerDelegationRouter.ts
packages/backend-for-frontend/src/services/delegationService.ts
packages/backend-for-frontend/src/utilities/errorMappers.ts

Closes [PIN-5372](https://pagopa.atlassian.net/browse/PIN-5372) 
This PR add routes in BFF to allow delegation process API usages.
All API are tested using bruno collection
✅  Create Delegation 
✅  Approve Delegation 
✅  Reject Delegation 
✅  Revoke Delegation
✅  Get Delegation by Id
✅  Get Delegations 
[PIN-5372]: https://pagopa.atlassian.net/browse/PIN-5372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN-5372 BFF delegation routers

---

packages/anac-certified-attributes-importer/src/config/config.ts
packages/anac-certified-attributes-importer/src/config/sftpConfig.ts
packages/datalake-data-export/src/index.ts
packages/ivass-certified-attributes-importer/src/config/config.ts

Closes [PIN-5565](https://pagopa.atlassian.net/browse/PIN-5565) [PIN-5567](https://pagopa.atlassian.net/browse/PIN-5567)
[PIN-5565]: https://pagopa.atlassian.net/browse/PIN-5565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PIN-5567]: https://pagopa.atlassian.net/browse/PIN-5567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN 5565, 5567 - ANAC and IVASS config

---

packages/agreement-platformstate-writer/package.json
packages/dtd-catalog-exporter/package.json
packages/one-trust-notices/package.json
pnpm-lock.yaml

Removing leftover TS node usages in favor of TSX

---

packages/api-clients/open-api/bffApi.yml
packages/api-clients/open-api/tenantApi.yml
packages/api-clients/template-bff.hbs
packages/backend-for-frontend/src/routers/tenantRouter.ts
packages/backend-for-frontend/src/services/tenantService.ts
packages/models/src/tenant/tenant.ts
packages/tenant-process/src/model/domain/apiConverter.ts
packages/tenant-process/src/routers/TenantRouter.ts
packages/tenant-process/src/services/readModelService.ts
packages/tenant-process/src/services/tenantService.ts
packages/tenant-process/test/getTenants.test.ts

Closes [PIN-5641](https://pagopa.atlassian.net/browse/PIN-5641)
[PIN-5641]: https://pagopa.atlassian.net/browse/PIN-5641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN-5641 - Add features filter in get tenants

---

packages/api-clients/open-api/bffApi.yml
packages/api-clients/open-api/catalogApi.yml
packages/backend-for-frontend/src/routers/catalogRouter.ts
packages/backend-for-frontend/src/services/catalogService.ts
packages/catalog-process/src/model/domain/models.ts
packages/catalog-process/src/routers/EServiceRouter.ts
packages/catalog-process/src/services/readModelService.ts
packages/catalog-process/test/getEservices.test.ts

Closes [PIN-5640](https://pagopa.atlassian.net/browse/PIN-5640)
[PIN-5640]: https://pagopa.atlassian.net/browse/PIN-5640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN-5640 - Add `delegated` filter in `GET /eservices`

---

packages/agreement-process/src/services/readModelService.ts
packages/agreement-process/test/getAgreementEservices.test.ts
packages/agreement-process/test/getAgreements.test.ts

PIN-5488 agreement listing

---

packages/api-gateway/src/services/readModelService.ts

Closes [PIN-5699](https://pagopa.atlassian.net/browse/PIN-5699)
[PIN-5699]: https://pagopa.atlassian.net/browse/PIN-5699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN-5699 - Fix producer keychain keys retrieving in api-gateway

---

packages/commons-test/src/testUtils.ts
packages/delegation-process/src/services/delegationProducerService.ts
packages/delegation-process/test/.eslintrc.json
packages/delegation-process/test/approveProducerDelegation.test.ts
packages/delegation-process/test/createProducerDelegation.test.ts
packages/delegation-process/test/rejectProducerDelegation.test.ts
packages/delegation-process/test/revokeProducerDelegation.test.ts
packages/models/src/delegation/delegation.ts

Fixing type of `who` in delegation process

---

packages/datalake-interface-exporter/.env
packages/datalake-interface-exporter/.env.test
packages/datalake-interface-exporter/src/config/config.ts
packages/datalake-interface-exporter/src/interfaceExporter.ts
packages/datalake-interface-exporter/test/interfaceExporter.test.ts

Adding prefix path config to interface exporter

---

packages/agreement-lifecycle/src/filters/attributesFilter.ts
packages/agreement-process/test/upgradeAgreement.test.ts
packages/agreement-process/test/verifiedAttributes.test.ts

This PR fix the flaky tests happening inside `upgradeAgreement` service test suite.
Also includes a fixes logic inside `isVerificationExpired` function.

PIN-5779 - Fix `upgradeAgreement` flaky test

---

packages/delegation-process/Dockerfile

This PR add puppteer dependencies in Dockerfile for Delegation Process.

Fix Puppeteer dependencies in Docker file for delegation process

---

collections/delegation/consumer/Revokes a consumer delegation.bru
packages/api-clients/open-api/delegationApi.yml
packages/delegation-process/src/model/domain/models.ts
packages/delegation-process/src/model/domain/toEvent.ts
packages/delegation-process/src/resources/templates/delegationRevokedTemplate.html
packages/delegation-process/src/routers/DelegationConsumerRouter.ts
packages/delegation-process/src/services/delegationConsumerService.ts
packages/delegation-process/src/services/delegationContractBuilder.ts
packages/delegation-process/test/revokeConsumerDelegation.test.ts
packages/delegation-process/test/revokeProducerDelegation.test.ts
packages/delegation-readmodel-writer/src/delegationConsumerServiceV2.ts
packages/delegation-readmodel-writer/test/consumerServiceV2.test.ts
packages/models/proto/v2/delegation/events.proto
packages/models/src/delegation/delegationEvents.ts

Based on #1210 
Closes [PIN-5665](https://pagopa.atlassian.net/browse/PIN-5665)
These are the PDFs created by the approval for Consumer and Producer delegations:
[20241126142933_delegation_revocation_contract.pdf](https://github.com/user-attachments/files/17920192/20241126142933_delegation_revocation_contract.pdf)
[20241126142915_delegation_revocation_contract.pdf](https://github.com/user-attachments/files/17920198/20241126142915_delegation_revocation_contract.pdf)
[PIN-5665]: https://pagopa.atlassian.net/browse/PIN-5665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN-5665 - Revoke consumer delegation

---

packages/backend-for-frontend/src/api/catalogApiConverter.ts
packages/backend-for-frontend/src/services/catalogService.ts

Requested by the frontend team

Add waiting for approval descriptors in  BFF`draftDescriptors` property

---

packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/services/agreementStateProcessor.ts

This PR fixed an issue with the re-activation of a suspended agreement related to a producer delegated e-service

Fix delegated eservice agreement activation from suspension

---

.vscode/settings.json
packages/agreement-outbound-writer/package.json
packages/api-clients/open-api/bffApi.yml
packages/api-clients/open-api/catalogApi.yml
packages/authorization-updater/src/index.ts
packages/backend-for-frontend/src/routers/catalogRouter.ts
packages/backend-for-frontend/src/services/catalogService.ts
packages/catalog-outbound-writer/package.json
packages/catalog-outbound-writer/src/converters/toOutboundEventV2.ts
packages/catalog-platformstate-writer/src/consumerServiceV2.ts
packages/catalog-process/src/model/domain/errors.ts
packages/catalog-process/src/model/domain/toEvent.ts
packages/catalog-process/src/routers/EServiceRouter.ts
packages/catalog-process/src/services/catalogService.ts
packages/catalog-process/src/utilities/errorMappers.ts
packages/catalog-process/test/updateDescriptorAttributes.test.ts
packages/catalog-readmodel-writer/src/consumerServiceV2.ts
packages/models/proto/v2/eservice/events.proto
packages/models/src/eservice/eserviceEvents.ts
packages/notifier-seeder/src/models/catalog/catalogItemEventNotificationConverter.ts
packages/notifier-seeder/src/models/catalog/catalogItemEventNotificationMessage.ts
packages/purpose-outbound-writer/package.json
packages/tenant-outbound-writer/package.json
pnpm-lock.yaml

Update outbound model to 1.0.11 before merge ([outbound PR release](https://github.com/pagopa/interop-outbound-models/pull/20))

[HOTFIX] PIN-5746 - In-Add Attributes

---

package.json
packages/authorization-process/src/routers/AuthorizationRouter.ts
packages/client-purpose-updater/.env
packages/client-purpose-updater/Dockerfile
packages/client-purpose-updater/package.json
packages/client-purpose-updater/src/clientPurposeUpdaterConsumerServiceV2.ts
packages/client-purpose-updater/src/clients/clientsProvider.ts
packages/client-purpose-updater/src/config/config.ts
packages/client-purpose-updater/src/index.ts
packages/client-purpose-updater/tsconfig.check.json
packages/client-purpose-updater/tsconfig.json
pnpm-lock.yaml

I opened this other PR for changing the base branch from develop to main.
Tests will be added later with another PR
REF: #1261

PIN-5790 client-purpose-updater-consumer

---

packages/api-clients/open-api/bffApi.yml
packages/backend-for-frontend/src/api/delegationApiConverter.ts
packages/backend-for-frontend/src/services/delegationService.ts

The producer delegation eservice might be deleted by the delegator after it has been revoked. 
This PR adds logic that handles that case

PIN-5796 - Added missing e-service handling in enhance delegation bff function

---

packages/agreement-outbound-writer/package.json
packages/authorization-updater/src/index.ts
packages/catalog-outbound-writer/package.json
packages/catalog-outbound-writer/src/converters/toOutboundEventV2.ts
packages/catalog-platformstate-writer/src/consumerServiceV2.ts
packages/catalog-process/src/model/domain/toEvent.ts
packages/catalog-process/src/services/catalogService.ts
packages/catalog-process/test/approveDelegatedEServiceDescriptor.test.ts
packages/catalog-process/test/publishDescriptor.test.ts
packages/catalog-process/test/rejectDelegatedEServiceDescriptor.test.ts
packages/catalog-readmodel-writer/src/consumerServiceV2.ts
packages/datalake-interface-exporter/src/interfaceExporterV2.ts
packages/models/proto/v2/eservice/events.proto
packages/models/src/eservice/eserviceEvents.ts
packages/notifier-seeder/src/models/catalog/catalogItemEventNotificationConverter.ts
packages/notifier-seeder/src/models/catalog/catalogItemEventNotificationMessage.ts
packages/purpose-outbound-writer/package.json
packages/tenant-outbound-writer/package.json
pnpm-lock.yaml

`EServiceDescriptorDelegateSubmitted` -> `EServiceDescriptorSubmittedByDelegate`
`EServiceDescriptorDelegatorApproved` -> `EServiceDescriptorApprovedByDelegator`
`EServiceDescriptorDelegatorRejected` -> `EServiceDescriptorRejectedByDelegator`

Updated delegator eservice event names

---

packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/test/createAgreement.test.ts

See https://pagopa.atlassian.net/browse/PIN-5858 for more details.
* Before the fix the two tests (the one modified, and the new one) failed ❌ 
* After the fix the two tests are passing ✅

PIN-5858 - Agreement creation conflict check fix

---

packages/agreement-lifecycle/src/utils/verifiedAttributes.ts
packages/agreement-process/src/model/domain/models.ts
packages/agreement-process/src/resources/templates/documents/agreementContractTemplate.html
packages/agreement-process/src/services/agreementContractBuilder.ts
packages/agreement-process/test/activateAgreement.test.ts
packages/agreement-process/test/submitAgreement.test.ts
packages/agreement-process/test/upgradeAgreement.test.ts

Small fixes after manual testing.
[69e2865e-65ab-4e48-a638-2037a9ee2ee7_69e2865e-65ab-4e48-a638-2037a9ee2ee7_20241216175658_agreement_contract.pdf](https://github.com/user-attachments/files/18154102/69e2865e-65ab-4e48-a638-2037a9ee2ee7_69e2865e-65ab-4e48-a638-2037a9ee2ee7_20241216175658_agreement_contract.pdf)
[69e2865e-65ab-4e48-a638-2037a9ee2ee7_69e2865e-65ab-4e48-a638-2037a9ee2ee7_20241216180226_agreement_contract.pdf](https://github.com/user-attachments/files/18154180/69e2865e-65ab-4e48-a638-2037a9ee2ee7_69e2865e-65ab-4e48-a638-2037a9ee2ee7_20241216180226_agreement_contract.pdf)

PIN-5609 - Agreement activation contract fixes for Incaricato

---

collections/bff/tenants/get Tenants.bru
collections/tenant/Tenants.bru
packages/api-clients/open-api/bffApi.yml
packages/api-clients/open-api/tenantApi.yml
packages/delegation-process/src/services/validators.ts
packages/models/src/tenant/tenant.ts
packages/tenant-process/src/model/domain/apiConverter.ts
packages/tenant-process/src/utilities/errorMappers.ts
packages/tenant-process/test/getTenants.test.ts

PIN-5743 - Adding tenant feature DelegatedConsumer to tenants filter

---

packages/delegation-process/src/routers/DelegationRouter.ts
packages/delegation-process/src/services/delegationService.ts
packages/delegation-process/src/services/readModelService.ts
packages/delegation-process/test/getDelegations.test.ts

[Closes PIN-5875](https://pagopa.atlassian.net/browse/PIN-5875)
This PR fixes the `getDelegations` pagination in the `delegation-process`

PIN-5875 - Fix Delegations pagination

---

packages/agreement-process/test/cloneAgreement.test.ts

Closes [PIN-5757](https://pagopa.atlassian.net/browse/PIN-5757)
[PIN-5757]: https://pagopa.atlassian.net/browse/PIN-5757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN 5757 - Add clone agreement test on consumer delegate

---

packages/agreement-process/test/agreementConsumerDocuments.test.ts

Closes [PIN-5758](https://pagopa.atlassian.net/browse/PIN-5758)
[PIN-5758]: https://pagopa.atlassian.net/browse/PIN-5758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN 5758 - Add create agreement consumer document test

---

packages/agreement-process/test/activateAgreement.test.ts
packages/agreement-process/test/submitAgreement.test.ts
packages/agreement-process/test/utils.ts

New automated tests work ✅ 
The same call succeeds after the delegation is revoked ✅

PIN-5761 - Submit agreement delegate tests

---

packages/agreement-platformstate-writer/src/consumerServiceV1.ts
packages/agreement-platformstate-writer/test/consumerServiceV1.integration.test.ts

Fixed `agreement-platformstate-writer`

IMN-791 - Fix agreement-platformstate-writer

---

packages/dtd-catalog-exporter/src/models/converters.ts
packages/dtd-catalog-exporter/src/models/models.ts
packages/dtd-catalog-exporter/test/exportDtdPublicCatalog.test.ts

Requester from the FE team for a change in the catalog landing page

Added `producerId` in `PublicEService` dtd data export

---

packages/agreement-platformstate-writer/src/consumerServiceV1.ts
packages/agreement-platformstate-writer/src/consumerServiceV2.ts
packages/agreement-platformstate-writer/test/consumerServiceV1.integration.test.ts
packages/agreement-platformstate-writer/test/consumerServiceV2.integration.test.ts

This pull request is for fixing the upgrade timestamp in `agreement-platformstate-writer`.

Fix agreement timestamp for upgrade

---

packages/authorization-platformstate-writer/src/consumerServiceV1.ts
packages/authorization-platformstate-writer/src/consumerServiceV2.ts
packages/authorization-platformstate-writer/src/utils.ts
packages/authorization-platformstate-writer/test/consumerServiceV1.integration.test.ts
packages/authorization-platformstate-writer/test/consumerServiceV2.integration.test.ts
packages/authorization-platformstate-writer/test/utils.test.ts

Added debugging logs in `authorization-platformstate-writer` for `token-generation-states` write and delete functions

Add debugging logs in authorization-platformstate-writer

---

packages/api-clients/open-api/bffApi.yml
packages/backend-for-frontend/src/services/agreementService.ts

[Closes [PIN-5917](https://pagopa.atlassian.net/browse/PIN-5917)]
Sadly I am momentarily unable to test the BFF through bruno since I have a problem with the file manager that prevents me from starting the BFF
[PIN-5917]: https://pagopa.atlassian.net/browse/PIN-5917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Pin 5917: add delegate contactMail to agreement

---

packages/api-clients/open-api/bffApi.yml
packages/api-clients/open-api/purposeApi.yml
packages/purpose-process/src/model/domain/errors.ts
packages/purpose-process/src/routers/PurposeRouter.ts
packages/purpose-process/src/services/purposeService.ts
packages/purpose-process/src/services/readModelService.ts
packages/purpose-process/src/services/validators.ts
packages/purpose-process/src/utilities/errorMappers.ts

This PR updates the default retrieval mode for delegations using the `delegationId`, ensuring proper handling of cases where the delegation is not found. 
Additionally, it adds missing response codes and improves error mapping through updates to the error mappers.

Improve purpose delegation handling

---

packages/agreement-outbound-writer/package.json
packages/api-clients/open-api/catalogApi.yml
packages/authorization-updater/src/index.ts
packages/catalog-outbound-writer/src/converters/toOutboundEventV2.ts
packages/catalog-platformstate-writer/src/consumerServiceV2.ts
packages/catalog-process/src/model/domain/toEvent.ts
packages/catalog-process/src/routers/EServiceRouter.ts
packages/catalog-process/src/services/catalogService.ts
packages/catalog-process/src/utilities/errorMappers.ts
packages/catalog-process/test/updateEServiceName.test.ts
packages/catalog-readmodel-writer/src/consumerServiceV2.ts
packages/catalog-readmodel-writer/test/catalogReadmodelWriter.integration.test.ts
packages/models/proto/v2/eservice/events.proto
packages/models/src/eservice/eserviceEvents.ts
packages/notifier-seeder/src/models/catalog/catalogItemEventNotificationConverter.ts
packages/notifier-seeder/src/models/catalog/catalogItemEventNotificationMessage.ts

This pull request is for implementing the endpoint to update the name of an eservice, after the publication.

PIN-5893 Add eservice name update

---

packages/agreement-outbound-writer/package.json
packages/catalog-outbound-writer/package.json
packages/catalog-outbound-writer/src/converters/toOutboundEventV2.ts
packages/purpose-outbound-writer/package.json
packages/tenant-outbound-writer/package.json
pnpm-lock.yaml

This pull request is for using the latest versino of `outbound-models`

Fix outbound-models

---

packages/agreement-outbound-writer/package.json
packages/api-clients/open-api/bffApi.yml
packages/api-clients/open-api/catalogApi.yml
packages/authorization-updater/src/index.ts
packages/backend-for-frontend/src/routers/catalogRouter.ts
packages/backend-for-frontend/src/services/catalogService.ts
packages/catalog-outbound-writer/package.json
packages/catalog-outbound-writer/src/converters/toOutboundEventV2.ts
packages/catalog-platformstate-writer/src/consumerServiceV2.ts
packages/catalog-process/src/model/domain/toEvent.ts
packages/catalog-process/src/routers/EServiceRouter.ts
packages/catalog-process/src/services/catalogService.ts
packages/catalog-process/src/utilities/errorMappers.ts
packages/catalog-process/test/updateEServiceName.test.ts
packages/catalog-readmodel-writer/src/consumerServiceV2.ts
packages/catalog-readmodel-writer/test/catalogReadmodelWriter.integration.test.ts
packages/models/proto/v2/eservice/events.proto
packages/models/src/eservice/eserviceEvents.ts
packages/notifier-seeder/src/models/catalog/catalogItemEventNotificationConverter.ts
packages/notifier-seeder/src/models/catalog/catalogItemEventNotificationMessage.ts
packages/purpose-outbound-writer/package.json
packages/tenant-outbound-writer/package.json
pnpm-lock.yaml

This pull request contains the implementation of the new feature: `update eservice name after publication`.

PIN-5891 Feature: add eservice name update

---

packages/purpose-process/src/model/domain/models.ts
packages/purpose-process/src/resources/templates/documents/riskAnalysisTemplate.html
packages/purpose-process/src/services/purposeService.ts
packages/purpose-process/src/services/riskAnalysisDocumentBuilder.ts
packages/purpose-process/test/activatePurposeVersion.test.ts
packages/purpose-process/test/createPurposeVersion.test.ts

[Closes [PIN-5910](https://pagopa.atlassian.net/browse/PIN-5910)]
[PIN-5910]: https://pagopa.atlassian.net/browse/PIN-5910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Pin 5910: incaricato new risk analysis template

---

packages/api-clients/open-api/bffApi.yml
packages/api-clients/open-api/catalogApi.yml
packages/backend-for-frontend/src/services/catalogService.ts
packages/catalog-process/src/model/domain/models.ts
packages/catalog-process/src/routers/EServiceRouter.ts
packages/catalog-process/src/services/catalogService.ts
packages/catalog-process/src/services/readModelService.ts
packages/catalog-process/test/getEservices.test.ts

[Closes [PIN-6007](https://pagopa.atlassian.net/browse/PIN-6007)]
[PIN-6007]: https://pagopa.atlassian.net/browse/PIN-6007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Pin 6007: add is delegable filter in getEservices

---

packages/authorization-process/src/model/domain/errors.ts
packages/authorization-process/src/routers/AuthorizationRouter.ts
packages/authorization-process/src/services/authorizationService.ts
packages/authorization-process/src/services/readModelService.ts
packages/authorization-process/src/services/validators.ts
packages/authorization-process/src/utilities/errorMappers.ts
packages/authorization-process/test/addClientPurpose.test.ts
packages/authorization-process/test/utils.ts

Closes [PIN-5621](https://pagopa.atlassian.net/browse/PIN-5621)
[PIN-5621]: https://pagopa.atlassian.net/browse/PIN-5621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN 5621 - Delegate add purpose to client

---

packages/agreement-process/src/services/readModelService.ts
packages/purpose-process/src/services/readModelService.ts
packages/purpose-process/test/getPurposes.test.ts

Closes [PIN-5616](https://pagopa.atlassian.net/browse/PIN-5616)
[PIN-5616]: https://pagopa.atlassian.net/browse/PIN-5616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN 5616 - changes purpose listing

---

packages/api-clients/open-api/bffApi.yml
packages/backend-for-frontend/src/api/catalogApiConverter.ts
packages/backend-for-frontend/src/services/catalogService.ts

Closes [PIN-5748](https://pagopa.atlassian.net/browse/PIN-5748)
[PIN-5748]: https://pagopa.atlassian.net/browse/PIN-5748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN 5748 - Remove has certified attributes

---

packages/agreement-process/src/model/domain/agreement-validators.ts
packages/agreement-process/src/model/domain/errors.ts
packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/utilities/errorMappers.ts
packages/agreement-process/test/activateAgreement.test.ts
packages/agreement-process/test/agreementConsumerDocuments.test.ts
packages/agreement-process/test/archiveAgreement.test.ts
packages/agreement-process/test/cloneAgreement.test.ts
packages/agreement-process/test/createAgreement.test.ts
packages/agreement-process/test/deleteAgreement.test.ts
packages/agreement-process/test/rejectAgreement.test.ts
packages/agreement-process/test/submitAgreement.test.ts
packages/agreement-process/test/suspendAgreement.test.ts
packages/agreement-process/test/updateAgreement.test.ts
packages/agreement-process/test/upgradeAgreement.test.ts
packages/agreement-process/test/verifyTenantCertifiedAttributes.test.ts
packages/api-clients/open-api/agreementApi.yml
packages/api-clients/open-api/bffApi.yml
packages/purpose-process/src/services/purposeService.ts
packages/purpose-process/src/services/validators.ts

[Closes [PIN-5936](https://pagopa.atlassian.net/browse/PIN-5936)]
[PIN-5936]: https://pagopa.atlassian.net/browse/PIN-5936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN-5936: added better errors in agreement-process

---

packages/api-clients/open-api/bffApi.yml
packages/backend-for-frontend/src/services/agreementService.ts
packages/backend-for-frontend/src/services/catalogService.ts

Closes [PIN-6042](https://pagopa.atlassian.net/browse/PIN-6042)
[PIN-6042]: https://pagopa.atlassian.net/browse/PIN-6042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN 6042 - Sandardize isDelegated usages in BFF

---

packages/api-clients/open-api/bffApi.yml
packages/backend-for-frontend/src/api/catalogApiConverter.ts
packages/backend-for-frontend/src/api/eserviceTemplateApiConverter.ts
packages/backend-for-frontend/src/model/errors.ts
packages/backend-for-frontend/src/routers/eserviceTemplateRouter.ts
packages/backend-for-frontend/src/services/catalogService.ts
packages/backend-for-frontend/src/services/eserviceTemplateService.ts
packages/backend-for-frontend/src/utilities/errorMappers.ts
packages/eservice-template-process/src/routers/EServiceTemplateRouter.ts
packages/eservice-template-process/src/services/eserviceTemplateService.ts
packages/eservice-template-process/test/getEServiceTemplateById.test.ts

Closes [PIN-6003](https://pagopa.atlassian.net/browse/PIN-6003)
[PIN-6003]: https://pagopa.atlassian.net/browse/PIN-6003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN-6003 - Added get e-service template by id service

---

packages/backend-for-frontend/src/services/catalogService.ts

Closes [PIN-6133](https://pagopa.atlassian.net/browse/PIN-6133)
[PIN-6133]: https://pagopa.atlassian.net/browse/PIN-6133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN 6133 - Fix Import eservice

---

packages/delegation-process/src/services/readModelService.ts

Update the query structure to ensure compatibility with DocumentDB by modifying the lookup and matching logic.

PIN-6148: getConsumerDelegatorsWithAgreements Aggregation stage not supported

---

packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/services/readModelService.ts
packages/agreement-process/test/internalArchiveAgreementAfterDelegationRevocation.test.ts
packages/agreement-process/test/internalDeleteAgreementAfterDelegationRevocation.test.ts
packages/delegation-items-archiver/src/delegationItemsArchiverConsumerServiceV2.ts
packages/delegation-process/src/utilities/errorMappers.ts
packages/purpose-process/src/services/purposeService.ts
packages/purpose-process/test/internalArchivePurposeVersionAfterRevocation.test.ts
packages/purpose-process/test/internalDeletePurposeAfterRevocation.test.ts

Eliminate unnecessary delegation retrieval logic

PIN-6154: Purpose not archived after delegation revoked

---

collections/environments/PagoPA local.bru
collections/eservice-template/Create EService Template.bru
collections/eservice-template/Update EService Template.bru
package.json
packages/api-clients/open-api/bffApi.yml
packages/api-clients/open-api/eserviceTemplateApi.yml
packages/backend-for-frontend/src/api/eserviceTemplateApiConverter.ts
packages/backend-for-frontend/src/routers/eserviceTemplateRouter.ts
packages/backend-for-frontend/src/services/eserviceTemplateService.ts
packages/commons-test/src/testUtils.ts
packages/eservice-template-process/.env
packages/eservice-template-process/src/model/domain/apiConverter.ts
packages/eservice-template-process/src/model/domain/errors.ts
packages/eservice-template-process/src/model/domain/toEvent.ts
packages/eservice-template-process/src/routers/EServiceTemplateRouter.ts
packages/eservice-template-process/src/services/eserviceTemplateService.ts
packages/eservice-template-process/src/services/validators.ts
packages/eservice-template-process/src/utilities/errorMappers.ts
packages/eservice-template-process/test/createEServiceTemplate.test.ts
packages/eservice-template-process/test/updateEServiceTemplate.test.ts
packages/eservice-template-process/test/utils.ts
packages/models/src/eservice-template/protobufConverterToV2.ts

[PIN-5979](https://pagopa.atlassian.net/browse/PIN-5979)
[PIN-5979]: https://pagopa.atlassian.net/browse/PIN-5979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN-5980 create edit template

---

packages/delegation-process/src/services/readModelService.ts

[Closes [PIN-6163](https://pagopa.atlassian.net/browse/PIN-6163)]
Update the agreement lookup logic in the readModelService to be compatible with DocumentDB
[PIN-6163]: https://pagopa.atlassian.net/browse/PIN-6163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN-6163: Refactor getConsumerEservices for DocumentDB compatibility

---

packages/delegation-process/src/model/domain/models.ts
packages/delegation-process/src/resources/templates/delegationApprovedTemplate.html
packages/delegation-process/src/resources/templates/delegationRevokedTemplate.html
packages/delegation-process/src/services/delegationContractBuilder.ts
packages/delegation-process/test/approveDelegation.test.ts
packages/delegation-process/test/revokeDelegation.test.ts

[PIN-6168](https://pagopa.atlassian.net/browse/PIN-6168)
[20250212150313_delegation_activation_contract.pdf](https://github.com/user-attachments/files/18769042/20250212150313_delegation_activation_contract.pdf)
[20250212150444_delegation_revocation_contract.pdf](https://github.com/user-attachments/files/18769041/20250212150444_delegation_revocation_contract.pdf)
[20250212150555_delegation_activation_contract.pdf](https://github.com/user-attachments/files/18769036/20250212150555_delegation_activation_contract.pdf)
[20250212150557_delegation_revocation_contract.pdf](https://github.com/user-attachments/files/18769040/20250212150557_delegation_revocation_contract.pdf)
[PIN-6168]: https://pagopa.atlassian.net/browse/PIN-6168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoi …

PIN-6168 - Fixes to delegation contracts

---

collections/eservice-template/Publish EService Template Version.bru
packages/api-clients/open-api/bffApi.yml
packages/api-clients/open-api/eserviceTemplateApi.yml
packages/backend-for-frontend/src/routers/eserviceTemplateRouter.ts
packages/backend-for-frontend/src/services/eserviceTemplateService.ts
packages/eservice-template-process/src/model/domain/errors.ts
packages/eservice-template-process/src/routers/EServiceTemplateRouter.ts
packages/eservice-template-process/src/services/eserviceTemplateService.ts
packages/eservice-template-process/src/utilities/errorMappers.ts
packages/eservice-template-process/test/publishEServiceTemplateVersion.test.ts

Closes [PIN-5984](https://pagopa.atlassian.net/browse/PIN-5984)
[PIN-5984]: https://pagopa.atlassian.net/browse/PIN-5984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN 5984 - Template publish

---

packages/ipa-certified-attributes-importer/src/index.ts
packages/ipa-certified-attributes-importer/test/tenantUpsertData.test.ts

[PIN-6196](https://pagopa.atlassian.net/browse/PIN-6196)
[PIN-6196]: https://pagopa.atlassian.net/browse/PIN-6196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN-6196 - IPA certified attributes importer - GPS category

---

packages/authorization-server/src/routers/AuthorizationServerRouter.ts
packages/authorization-server/src/services/tokenService.ts
packages/authorization-server/test/authorizationServer.integration.test.ts
packages/authorization-server/test/utils.ts

Temporary change to test if rate limiter is the performance bottleneck in the auth-server.

PIN-6201 - pt2 - Removing rate limiter from auth-server

---

packages/authorization-server/src/routers/AuthorizationServerRouter.ts

Temporary change to test if zodios is the performance bottleneck in the auth-server.

PIN-6201 - pt3 - Disabling zodios in auth server for performance tests

---

collections/bff/eserviceTemplate/Download EService Template Document.bru
collections/eservice-template/Get EService Template Document by TemplateVersion and DocumentId.bru
packages/api-clients/open-api/bffApi.yml
packages/api-clients/template-bff.hbs
packages/backend-for-frontend/src/routers/eserviceTemplateRouter.ts
packages/backend-for-frontend/src/services/eserviceTemplateService.ts
packages/eservice-template-process/src/model/domain/errors.ts
packages/eservice-template-process/src/routers/EServiceTemplateRouter.ts
packages/eservice-template-process/src/services/eserviceTemplateService.ts
packages/eservice-template-process/src/utilities/errorMappers.ts
packages/eservice-template-process/test/getEServiceTemplateVersionDocumentById.test.ts

Recupero del documento (_interface_ o _docs_) specificato nel path a partire da un eServiceTemplate nota la versione di riferimento.
Secondo specifiche "_il recupero dell’oggetto da s3 andrà eseguito nel layer BFF_".

Bke implementazione recupero documento

---

packages/agreement-process/src/model/domain/agreement-validators.ts

This fixes [PIN-4766](https://pagopa.atlassian.net/browse/PIN-4766) and [PIN-4767](https://pagopa.atlassian.net/browse/PIN-4767)
[PIN-4766]: https://pagopa.atlassian.net/browse/PIN-4766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PIN-4767]: https://pagopa.atlassian.net/browse/PIN-4767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN-4766 / PIN-4767 Fix agreement states for document change

---

packages/agreement-process/src/model/domain/agreement-validators.ts
packages/agreement-process/test/submitAgreement.test.ts

This fixes bug [PIN-4770](https://pagopa.atlassian.net/browse/PIN-4770)
[PIN-4770]: https://pagopa.atlassian.net/browse/PIN-4770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN-4770 Remove suspended from valid descriptor states on agreement submit

---

packages/api-clients/open-api/catalogApi.yml
packages/backend-for-frontend/src/api/catalogApiConverter.ts

Catalog Process API returns optional template reference data in responses.

Catalog process api expose template ref

---

packages/api-clients/open-api/bffApi.yml
packages/api-clients/open-api/catalogApi.yml
packages/backend-for-frontend/src/api/catalogApiConverter.ts
packages/backend-for-frontend/src/routers/catalogRouter.ts
packages/backend-for-frontend/src/services/catalogService.ts
packages/backend-for-frontend/src/services/eserviceTemplateService.ts
packages/backend-for-frontend/src/utilities/eserviceDocumentUtils.ts
packages/catalog-process/src/model/domain/apiConverter.ts
packages/catalog-process/src/services/catalogService.ts
packages/catalog-process/test/createEServiceFromTemplate.test.ts
packages/catalog-process/test/uploadDocument.test.ts

Closes [PIN-6288](https://pagopa.atlassian.net/browse/PIN-6288)
This PR enhances returned template data in eservice in endpoint `/producers/eservices/{eserviceId}/descriptors/{descriptorId}` .
✅  Tests updates
[PIN-6288]: https://pagopa.atlassian.net/browse/PIN-6288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN-6288 BFF enhance eservice with template data

---

packages/commons-test/src/containerTestUtils.ts

The developers of aws ses local published a broken version of the package. I fixed the version with the last working. 
https://github.com/domdomegg/aws-ses-v2-local/issues/36

Fix version of aws ses local

---

packages/api-clients/open-api/bffApi.yml
packages/backend-for-frontend/src/api/catalogApiConverter.ts
packages/backend-for-frontend/src/services/catalogService.ts

FE team asked to receive the info of a new template version available.
This info has been inserted inside the following bff models: 
- `EServiceTemplateRef`
- `ProducerEService`

Added `isNewTemplateVersionAvailable` to instances models in bff

---

collections/bff/catalog/Create EService Instance From Template.bru
collections/bff/catalog/Upgrade Eservice Template Instance.bru
collections/catalog/Create EService from existing Template.bru
collections/catalog/Upgrade Eservice Template Instance.bru
packages/api-clients/open-api/bffApi.yml
packages/api-clients/open-api/catalogApi.yml
packages/backend-for-frontend/src/routers/catalogRouter.ts
packages/catalog-process/src/routers/EServiceRouter.ts

Resolves:
- https://github.com/pagopa/interop-be-monorepo/pull/1487#discussion_r1977575102
- https://github.com/pagopa/interop-be-monorepo/pull/1487#discussion_r1977576750

Fix create eservice from template and upgrade route

---

packages/api-clients/open-api/eserviceTemplateApi.yml
packages/backend-for-frontend/src/services/catalogService.ts
packages/backend-for-frontend/src/services/eserviceTemplateService.ts
packages/eservice-template-process/src/routers/EServiceTemplateRouter.ts

This PR addresses [this](https://github.com/pagopa/interop-be-monorepo/pull/1487#discussion_r1977603788) comment

Updated eservice template API spec paths

---

packages/purpose-process/src/services/purposeService.ts
packages/purpose-process/src/services/validators.ts
packages/purpose-process/test/clonePurpose.test.ts

Ticket Jira: https://pagopa.atlassian.net/browse/PIN-4759

Fixed archived purpose cannot be cloned

---

docker/local-kms-seed/jwks.json

This PR replaces the key used locally for verifying the token.

Fix local signing key

---

packages/eservice-template-process/src/routers/EServiceTemplateRouter.ts
packages/eservice-template-process/src/utilities/errorMappers.ts

Closes [PIN-6483](https://pagopa.atlassian.net/browse/PIN-6483)
[PIN-6483]: https://pagopa.atlassian.net/browse/PIN-6483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN-6483 Fix error mappers

---

packages/agreement-process/src/routers/AgreementRouter.ts

Review with hide whitespace diff

PIN-5750 Style refactor agreeement router

---

packages/catalog-process/src/services/readModelService.ts
packages/catalog-process/test/getEservices.test.ts

[Closes [PIN-6486](https://pagopa.atlassian.net/browse/PIN-6486)]
[PIN-6486]: https://pagopa.atlassian.net/browse/PIN-6486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN-6486: fix getEservices isConsumerDelegable filter

---

packages/backend-for-frontend/src/routers/catalogRouter.ts
packages/backend-for-frontend/src/services/catalogService.ts
packages/backend-for-frontend/src/utilities/errorMappers.ts

[Closes PIN-6502](https://pagopa.atlassian.net/browse/PIN-6502)

PIN-6502 - Added 404 error if template not exists in get e-service template instances

---

packages/authorization-process/Dockerfile

Fix `Dockerfile` of authorization process. The missing package is needed for producing application-audit.

PIN-6146 Fix authorization-process audit

---

packages/api-gateway/src/api/tenantApiConverter.ts

[PIN-6527](https://pagopa.atlassian.net/browse/PIN-6527)
[PIN-6527]: https://pagopa.atlassian.net/browse/PIN-6527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN-6527: Fix wrong organization category in API GW

---

packages/commons/src/interop-token/utils.ts

[PIN-6564](https://pagopa.atlassian.net/browse/PIN-6564)
[PIN-6564]: https://pagopa.atlassian.net/browse/PIN-6564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN-6564: Fix JWT encoding issue

---

packages/purpose-process/src/routers/PurposeRouter.ts
packages/purpose-process/src/services/purposeService.ts
packages/purpose-process/src/services/validators.ts
packages/purpose-process/test/internalArchivePurposeVersionAfterRevocation.test.ts
packages/purpose-process/test/internalDeletePurposeAfterRevocation.test.ts

[PIN-6329](https://pagopa.atlassian.net/browse/PIN-6329) (covers only the purpose process)
Build & tests work for purpose-process:

PIN-6329 - Refactor/authorization purpose process

---

packages/api-gateway/src/routers/apiGatewayRouter.ts
packages/api-gateway/src/services/authorizationService.ts
packages/api-gateway/src/services/purposeService.ts
packages/api-gateway/src/utilities/context.ts
packages/backend-for-frontend/src/app.ts
packages/backend-for-frontend/src/routers/agreementRouter.ts
packages/backend-for-frontend/src/routers/attributeRouter.ts
packages/backend-for-frontend/src/routers/catalogRouter.ts
packages/backend-for-frontend/src/routers/clientRouter.ts
packages/backend-for-frontend/src/routers/consumerDelegationRouter.ts
packages/backend-for-frontend/src/routers/delegationRouter.ts
packages/backend-for-frontend/src/routers/eserviceTemplateRouter.ts
packages/backend-for-frontend/src/routers/privacyNoticeRouter.ts
packages/backend-for-frontend/src/routers/producerDelegationRouter.ts
packages/backend-for-frontend/src/routers/producerKeychainRouter.ts
packages/backend-for-frontend/src/routers/purposeRouter.ts
packages/backend-for-frontend/src/routers/supportRouter.ts
packages/backend-for-frontend/src/routers/tenantRouter.ts
packages/backend-for-frontend/src/services/authorizationService.ts
packages/backend-for-frontend/src/utilities/context.ts
packages/backend-for-frontend/src/utilities/middlewares.ts
packages/commons/src/auth/authorization.ts

[PIN-6329](https://pagopa.atlassian.net/browse/PIN-6329) (covers only the auth process)

PIN-6329 - Refactor/authorization BFF & API GW

---

packages/commons-test/src/testUtils.ts
packages/eservice-template-process/src/routers/EServiceTemplateRouter.ts
packages/eservice-template-process/src/services/eserviceTemplateService.ts
packages/eservice-template-process/src/services/readModelService.ts
packages/eservice-template-process/src/services/validators.ts
packages/eservice-template-process/test/getEServiceTemplateById.test.ts
packages/eservice-template-process/test/getEServiceTemplates.test.ts

[PIN-6329](https://pagopa.atlassian.net/browse/PIN-6329) (covers only the e-service template process)
Build & tests work for eservice-template-process:

PIN-6329 - Refactor/authorization e-service template process

---

packages/delegation-process/src/routers/DelegationRouter.ts
packages/delegation-process/src/services/delegationService.ts
packages/delegation-process/src/services/readModelService.ts
packages/delegation-process/src/services/validators.ts
packages/delegation-process/test/getConsumerDelegators.test.ts
packages/delegation-process/test/getConsumerDelegatorsWithAgreements.test.ts
packages/delegation-process/test/getConsumerEservices.test.ts
packages/delegation-process/test/getDelegationById.test.ts
packages/delegation-process/test/getDelegations.test.ts

[PIN-6329](https://pagopa.atlassian.net/browse/PIN-6329) (covers only the delegation process)
Build & tests work for delegation-process:

PIN-6329 - Refactor/authorization delegation process

---

packages/commons-test/src/testUtils.ts
packages/tenant-process/src/routers/TenantRouter.ts
packages/tenant-process/src/services/tenantService.ts
packages/tenant-process/src/services/validators.ts
packages/tenant-process/test/addCertifiedAttribute.test.ts
packages/tenant-process/test/addCertifierId.test.ts
packages/tenant-process/test/addDeclaredAttribute.test.ts
packages/tenant-process/test/addTenantMail.test.ts
packages/tenant-process/test/deleteTenantMailById.test.ts
packages/tenant-process/test/getCertifiedAttributes.test.ts
packages/tenant-process/test/getTenantByExternalId.test.ts
packages/tenant-process/test/getTenantById.test.ts
packages/tenant-process/test/getTenantBySelfcareId.test.ts
packages/tenant-process/test/internalAssignCertifiedAttribute.test.ts
packages/tenant-process/test/internalRevokeCertifiedAttribute.test.ts
packages/tenant-process/test/internalUpsertTenant.test.ts
packages/tenant-process/test/m2mRevokeCertifiedAttribute.test.ts
packages/tenant-process/test/m2mUpsertTenant.test.ts
packages/tenant-process/test/maintenanceTenantDelete.test.ts
packages/tenant-process/test/revokeDeclaredAttribute.test.ts
packages/tenant-process/test/updateTenantDelegatedFeatures.test.ts
packages/tenant-process/test/updateTenantVerifiedAttribute.test.ts
packages/tenant-process/test/updateVerifiedAttributeExtensionDate.test.ts
packages/tenant-process/test/verifyVerifiedAttribute.test.ts

[PIN-6329](https://pagopa.atlassian.net/browse/PIN-6329) (covers only the tenant process)
Build & tests work for tenant-process:

PIN-6329 - Refactor/authorization tenant process

---

packages/tenant-process/src/routers/TenantRouter.ts
packages/tenant-process/src/services/tenantService.ts

Fixing regression after authdata refactor

---

packages/catalog-process/src/services/readModelServiceSQL.ts
packages/tenant-process/src/services/readModelServiceSQL.ts
packages/tenant-process/test/getConsumers.test.ts
packages/tenant-process/test/getProducers.test.ts

[Fix](https://pagopa.atlassian.net/browse/PIN-6855) regression error ([see](https://pagopa.atlassian.net/browse/PIN-6851))

PIN-6855: Fix readmodel sql part6

---

packages/selfcare-client-users-updater/src/services/selfcareClientUsersUpdaterProcessor.ts

This PR refactors the Kafka message handling flow by introducing an early validation step for `productId` before parsing the payload.
By doing so, we ensure that only messages relevant to the expected product are processed.
This change addresses issues like the following, where unrelated messages (e.g., with unexpected enum values such as `operator` in `productRole`) were causing errors:
`"message": "Invalid enum value. Expected 'admin' | 'security' | 'api' | 'support', received 'operator'"`

clientUsersUpdater: fix message parsing

---

packages/client-assertion-validation/src/errors.ts
packages/client-assertion-validation/src/validation.ts
packages/client-assertion-validation/test/validation.test.ts
packages/dpop-validation/src/errors.ts
packages/dpop-validation/src/validation.ts
packages/dpop-validation/test/validation.test.ts

This PR fixes the client assertion and DPoP multiline logs by converting them to one line strings.

PIN-7042 - Fix client assertion and DPoP invalid claims logs

---

packages/domains-analytics-writer/src/utils/sqlQueryHelper.ts

Fixes `"MERGE statement with single WHEN clause"` error by replacing `MERGE` with `DELETE FROM ... USING ....` to purge  obsolete records based on `metadata_version`.

Analytics: Resolve MERGE  deleting statement error

---

packages/tenant-process/src/services/tenantService.ts
packages/tenant-process/test/addTenantMail.test.ts

[Closes [PIN-7057](https://pagopa.atlassian.net/browse/PIN-7057)]
Update mail handling logic to ensure that only the latest mail of a specific kind is considered.
[PIN-7057]: https://pagopa.atlassian.net/browse/PIN-7057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN-7057: Refactor mail handling in tenant service

---

packages/tenant-process/src/services/tenantService.ts
packages/tenant-process/test/integration/addTenantMail.test.ts

Co-authored-by: Carmine Porricelli <carmine.porricelli@pagopa.it>

FixConflict_release_2.4.0

---

packages/eservice-template-process/src/model/domain/errors.ts
packages/eservice-template-process/src/services/eserviceTemplateService.ts
packages/eservice-template-process/src/utilities/errorMappers.ts
packages/eservice-template-process/test/api/createEServiceTemplateDocument.test.ts
packages/eservice-template-process/test/integration/uploadDocument.test.ts

[PIN-7378](https://pagopa.atlassian.net/browse/PIN-7378)
[PIN-7378]: https://pagopa.atlassian.net/browse/PIN-7378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN-7378 - Add mapping for checksumDuplicate error in e-service template document upload

---

collections/m2m gateway/eservices/Update published eservice delegation.bru
collections/m2m gateway/eservices/Update published eservice description.bru
collections/m2m gateway/eservices/Update published eservice name.bru
collections/m2m gateway/eservices/Upload eservice descriptor interface.bru
packages/api-clients/open-api/catalogApi.yml
packages/api-clients/open-api/m2mGatewayApi.yml
packages/catalog-process/src/routers/EServiceRouter.ts
packages/catalog-process/src/services/catalogService.ts
packages/catalog-process/test/api/updateEServiceName.test.ts
packages/catalog-process/test/api/updateEserviceDelegationFlags.test.ts
packages/catalog-process/test/api/updateEserviceDescription.test.ts
packages/catalog-process/test/integration/updateEServiceName.test.ts
packages/catalog-process/test/integration/updateEserviceDelegationFlags.test.ts
packages/catalog-process/test/integration/updateEserviceDescription.test.ts
packages/m2m-gateway/src/routers/eserviceRouter.ts
packages/m2m-gateway/src/services/eserviceService.ts
packages/m2m-gateway/test/api/eservices/updatePublishedEServiceDelegation.test.ts
packages/m2m-gateway/test/api/eservices/updatePublishedEServiceDescription.test.ts
packages/m2m-gateway/test/api/eservices/updatePublishedEServiceName.test.ts
packages/m2m-gateway/test/integration/eservices/updatePublishedEServiceDelegation.test.ts
packages/m2m-gateway/test/integration/eservices/updatePublishedEServiceDescription.test.ts
packages/m2m-gateway/test/integration/eservices/updatePublishedEServiceName.test.ts

[PIN-7250](https://pagopa.atlassian.net/browse/PIN-7250)
[PIN-7251](https://pagopa.atlassian.net/browse/PIN-7251)
[PIN-7252](https://pagopa.atlassian.net/browse/PIN-7252)
Implements the following routes in m2m gateway:
- `PATCH /eservices/{eserviceId}/name`
- `PATCH /eservices/{eserviceId}/delegation`
- `PATCH /eservices/{eserviceId}/description`
Checklist:
[PIN-7250]: https://pagopa.atlassian.net/browse/PIN-7250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PIN-7251]: https://pagopa.atlassian.net/browse/PIN-7251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PIN-7252]: https://pagopa.atlassian.net/browse/PIN-7252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …

PIN-7250 + PIN-7251 + PIN-7252 - M2M add PATCH endpoints to update published E-Service fields

---

packages/models/proto/v2/purpose-template/events.proto
packages/purpose-template-process/package.json
packages/purpose-template-readmodel-writer-sql/package.json
pnpm-lock.yaml

This PR adds the entire purpose template and e-service objects to the link/unlink events.

PIN-7532 - Update purpose template link/unlink events with the entire objects 

---

packages/domains-analytics-writer/src/service/setupDbService.ts
packages/domains-analytics-writer/src/utils/sqlQueryHelper.ts
packages/domains-analytics-writer/test/agreementService.test.ts

Added staging deduplication to handle SQL MERGE error: `Found multiple matches to update the same tuple`

PIN-7558: Analytics - Added staging deduplication
