db/local-db.yml

Set `wal_level` to `logical`, which is required for Debezium to be able to read the Postgres WAL.
To check if it's applied correctly, after restarting the DB, run `SHOW wal_level;` which should return `logical`.

Configure Postgres to work with Debezium

---

README.md
docker/docker-compose.yml
docker/pg-pass
docker/pg-servers.json
packages/catalog-process/scripts/db-destroy.sh
packages/catalog-process/scripts/db-start.sh
packages/catalog-process/scripts/db-stop.sh

Questa PR aggiunge un pgAdmin preconfigurato esposto sulla 8082, che è utile per ispezionare gli event store durante lo sviluppo locale

Add pgAdmin

---

docker/docker-compose.yml
packages/event-consumer/register-catalog-postgres.json
packages/event-consumer/scripts/infra-start.sh
packages/event-consumer/src/index.ts

Minor improvements to the event consumer:
- fix Mongo collection name
- simplify some Docker networking stuff now that all infra is in the same Docker Compose file
- disconnect the consumer when terminated with Ctrl-C

Event consumer improvements

---

.github/workflows/pr.yml

We're using node 16 in the CI but requiring `>= 18`

Update node version in the CI

---

packages/catalog-process/src/utilities/config.ts

Zod `discriminatedUnion` has some issues and in the future will be deprecated in favor of a new API called `switch`.
https://github.com/colinhacks/zod/issues/2106
Our current configuration doesn't work for this reason https://github.com/colinhacks/zod/issues/2637
An easy solution is to duplicate the entry for each value, for this reason, I removed the `optional()` and added `MOCK_FILE_MANAGER: z.undefined()` which should behave the same way as before without the error.

Fix config parser

---

.github/workflows/dev.yml

Revert Add GH caching in workflow during docker/build-push-action

---

packages/catalog-process/scripts/db-start.sh
packages/catalog-process/scripts/db-stop.sh
packages/catalog-process/src/app.ts

Close [PPA-34](https://buildo.atlassian.net/browse/PPA-34?atlOrigin=eyJpIjoiZWQ5MzRhNzM1NzJhNDBlMDkwM2YxNzEwYjBjMWI2MWIiLCJwIjoiaiJ9)
This PR silent all logs for healthy check route `/status` 
Also add ReadModel image when start infra locally with scripts, this read model db is necessary to running catalog-process locally.

Ppa 34 silent healthy status route logs

---

packages/commons/src/context/context.ts

This PR fix ContextData middleware when `authentication` isn't provided, in case of `health status` authentication is not required.
**ERROR**: ContextData middleware inject x-correlation-id from headers in context data, if not provided next function are not invoked.

Fix contextDataMiddleware

---

.eslintrc.cjs
packages/agreement-consumer/src/model/converter.ts
packages/catalog-consumer/src/model/converter.ts

This PR removes `ts-pattern` for protobuf enum mapping because it's impossible to use `exhaustive` (https://github.com/gvergnaud/ts-pattern/issues/183).
I added a check on the exhaustiveness of the `switch` and used that instead.

Refactor protobuf enum mapping

---

packages/agreement-consumer/.env
packages/catalog-consumer/.env

This PR adds a dedicated Kafka group for each `consumer` to avoid situations in which a consumer id is idle even if is connected to a topic with enough partitions

IMN 111- Fix kafka group

---

packages/agreement-consumer/package.json
packages/agreement-consumer/src/index.ts
packages/catalog-consumer/package.json
packages/catalog-consumer/src/index.ts
packages/kafka-iam-auth/README.md
packages/kafka-iam-auth/package.json
packages/kafka-iam-auth/src/constants.ts
packages/kafka-iam-auth/src/create-authenticator.ts
packages/kafka-iam-auth/src/create-mechanism.ts
packages/kafka-iam-auth/src/create-payload.ts
packages/kafka-iam-auth/src/create-sasl-authentication-request.ts
packages/kafka-iam-auth/src/create-sasl-authentication-response.ts
packages/kafka-iam-auth/src/index.ts
packages/kafka-iam-auth/tsconfig.json
packages/models/src/errors.ts
pnpm-lock.yaml

Close [IMN-82](https://pagopa.atlassian.net/browse/IMN-82?atlOrigin=eyJpIjoiZjdlMWY0ZDljZTZjNDBhYzhiMDIxMWQ5MmJlMGU1NjciLCJwIjoiaiJ9)
This PR remove definitively the library [@jm18457/kafkajs-msk-iam-authentication-mechanism](https://github.com/jmaver-plume/kafkajs-msk-iam-authentication-mechanism) from consumers services and introduce a new module `kafka-iam-auth` to create Kafka consumer's connection and authentication to topics.
Authentication mechanism for KafkaJS was implemented with same code of removed library, furthermore some specific custom errors like ours stack, was introduced.
With this new approach Authentication is scheduled to be re-executed approximately every hour.
Running a consumer is now simplified,  using a single function
```
await runConsumer(config, …
```

IMN-82 SALS Kafka consumers authentication mechanism

---

packages/agreement-process/src/app.ts
packages/agreement-process/src/model/domain/errors.ts
packages/agreement-process/src/model/types.ts
packages/agreement-process/src/routers/AgreementRouter.ts
packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/services/readModelService.ts
packages/agreement-process/src/services/validators.ts
packages/catalog-process/src/app.ts
packages/catalog-process/src/model/domain/errors.ts
packages/catalog-process/src/model/types.ts
packages/catalog-process/src/routers/EServiceRouter.ts
packages/catalog-process/src/services/catalogService.ts
packages/catalog-process/src/services/readModelService.ts
packages/catalog-process/src/utilities/versionGenerator.ts
packages/catalog-process/test/catalogService.test.ts
packages/commons/src/auth/authenticationMiddleware.ts
packages/commons/src/auth/authorizationMiddleware.ts
packages/commons/src/repositories/ReadModelRepository.ts
packages/models/src/errors.ts

- removed `makeApiError` functions and merged all the functionality into `makeApiProblem`
- removed `ProcessError`, `CatalogProcessError`, and `AgreementProcessError` in favor of a common `ApiError`
- removed `ErrorTypes`
- every `process` service declares its error types (via const or function that creates an `ApiError`). Some common error types remain inside the `models` package.
- Some `genericError` has an additional `detail` (see `readModelService` files)

IMN 113 - Errors refactor

---

packages/agreement-process/src/model/domain/errors.ts
packages/agreement-process/src/routers/AgreementRouter.ts
packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/services/agreementSubmissionProcessor.ts
packages/agreement-process/src/utilities/errorMappers.ts
packages/attribute-registry-process/src/model/domain/errors.ts
packages/attribute-registry-process/src/routers/AttributeRouter.ts
packages/attribute-registry-process/src/utilities/errorMappers.ts
packages/catalog-process/src/model/domain/errors.ts
packages/catalog-process/src/routers/EServiceRouter.ts
packages/catalog-process/src/services/catalogService.ts
packages/catalog-process/src/utilities/errorMappers.ts
packages/commons/src/auth/authenticationMiddleware.ts
packages/commons/src/auth/authorizationMiddleware.ts
packages/models/src/errors.ts
packages/tenant-process/src/model/domain/errors.ts
packages/tenant-process/src/routers/TenantRouter.ts
packages/tenant-process/src/utilities/errorMappers.ts

This PR removes the `httpCode` from `ApiError`. The `makeApiProblem` function that every router (and middleware) should use to create a `Problem`  now requires a function to map every `ApiError` with an `httpCode`.
Every process service should declare an `errorMappers.ts` file that contains the required functions (one for each route) that map the `ApiError` with the corresponding `httpCode`.
The `makeApiProblem` function is changed into a `makeApiProblemBuilder`. Each service that would use this function should create an instance `const makeApiProblem = makeApiProblemBuilder({ ... })` using as argument an object with the desired custom error code.
example:
```typescript
export const errorCodes = {
eServiceDescriptorNotFound: "0002",
eServiceDescriptorWithoutInterface: "0003", …
```

IMN 140 - Refactor error code

---

packages/agreement-process/src/services/readmodel/readModelService.ts

GET `/agreements` was not returning any agreement, even though I have two agreements in the mongo collection.
The only way to get some agreements is to specify ALL the following optional filters: eservicesIds, descriptorsIds, producersIds, consumersIds. In that case, you also see another bug: the totalCount is wrong, always `0`.
The total count now is correct:
And also, if I don't specify the filters above, it returns all agreements (paginated):

Fixing GET /agreements query

---

packages/agreement-process/kubernetes/dev/deployment.yaml
packages/agreement-readmodel-writer/kubernetes/dev/deployment.yaml
packages/catalog-process/kubernetes/dev/deployment.yaml
packages/catalog-readmodel-writer/kubernetes/dev/deployment.yaml
packages/tenant-consumer/kubernetes/dev/deployment.yaml

With last PR [IMN-155-agreement-services-CI ](https://github.com/pagopa/interop-be-monorepo/pull/133) **Build & Deploy** github action task throws the following error [detail here](https://github.com/pagopa/interop-be-monorepo/actions/runs/7407322434/job/20153308935).
```
error: error validating "deployment.yaml": error validating data: failed to check CRD: failed to list CRDs: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "buildo-gh-actions-interop-be-monorepo-105" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope; if you choose to ignore these errors, turn validation off with --validate=false
serviceaccount/interop-be-agreement-process-refactor created
```
The deployment.yaml files define fields `apiVersion` as …

Fix DEV CI add properly apiVersion value

---

packages/agreement-process/kubernetes/dev/configmap.yaml
packages/agreement-process/kubernetes/dev/deployment.yaml
packages/agreement-readmodel-writer/kubernetes/dev/deployment.yaml
packages/catalog-readmodel-writer/kubernetes/dev/deployment.yaml

With last PR [Fix DEV CI add properly apiVersion value ](https://github.com/pagopa/interop-be-monorepo/pull/143) **Build & Deploy** github action task throws the following error [detail here](https://github.com/pagopa/interop-be-monorepo/actions/runs/7409291657/job/20159259962).
```
error: The Deployment "interop-be-catalog-readmodel-writer" is invalid: spec.template.spec.containers[0].env[13].name: Required value
```
For the two services `catalog-readmode-writer` and `agreement-readmodel-writer` was added missed variables `KAFKA_TOPICS` into deployment.yaml files.

Add missing env variables config in deployment.yaml

---

packages/agreement-process/open-api/agreement-service-spec.yml
packages/agreement-process/src/model/domain/errors.ts
packages/agreement-process/src/model/domain/toEvent.ts
packages/agreement-process/src/model/domain/validators.ts
packages/agreement-process/src/routers/AgreementRouter.ts
packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/utilities/errorMappers.ts
packages/agreement-readmodel-writer/src/model/models.ts
packages/models/src/agreement/agreementEvents.ts

Close [IMN-33](https://pagopa.atlassian.net/browse/IMN-33)
This PR add API `/agreements/:agreementId/consumer-documents/:documentId` also add the message handler method in consumer service to update readmodel entity.
[IMN-33]: https://pagopa.atlassian.net/browse/IMN-33?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-33 post agreement consumer document

---

packages/agreement-readmodel-writer/src/model/converter.ts
packages/catalog-readmodel-writer/src/model/converter.ts

During events deserialization the Date field could be converted to start epoch date time `January 1st, 1970 at 00:00:00 UTC` if the input is a falsy value.
affected code
```
new Date(Number(input.createdAt))
```
this bug affects Agreement's event converter but also EService too, by the way Eservice protobuf definition contains some inconsistency with model definition, so temporary fix was applied and definitive fix should be solved with ISSUE [IMN-171](https://pagopa.atlassian.net/browse/IMN-171) that must be considerer as a breaking change.
Evaluate input and return `undefined` if is a falsy value otherwise return parsed number.
For EService converter a safeParser funciton was created, if the date was `undefined` the error will throws.
[IMN-171]: …

Fix date deserialization

---

packages/agreement-process/package.json
packages/agreement-process/src/model/domain/apiConverter.ts
packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/services/agreementSubmissionProcessor.ts
packages/agreement-process/src/services/pdfGenerator.ts
pnpm-lock.yaml

This PR removes the usage of the `utcToZonedTime` utility method in [date-fns-tz](https://github.com/marnusw/date-fns-tz) . Unlike what was explored previously, this method does not produce a correct UTC date 😅 , as creating new dates with the 'new Date()' command defaults to the UTC time zone. This means that only the stringified date value is affected by applying the local time zone of the machine from which it is executed.
Therefore, the value is simply replaced with the 'new Date()', which similarly generates a UTC date and don't needs manipulation.
----
However, there are two aspects that will need to be addressed in this [IMN-172](https://pagopa.atlassian.net/browse/IMN-172) JIRA ISSUE: 
First concerning the centralization into a single shared utility that can operates with dates …

Utc date creation remove

---

packages/agreement-process/open-api/agreement-service-spec.yml
packages/agreement-process/src/routers/AgreementRouter.ts
packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/services/agreementStampUtils.ts
packages/agreement-process/src/services/agreementStateProcessor.ts
packages/agreement-process/src/services/agreementSubmissionProcessor.ts
packages/agreement-process/src/services/agreementSuspensionProcessor.ts
packages/agreement-process/src/services/pdfGenerator.ts
packages/agreement-process/src/utilities/errorMappers.ts
packages/models/src/agreement/agreement.ts

Closes [IMN-36](https://pagopa.atlassian.net/browse/IMN-36)
[IMN-36]: https://pagopa.atlassian.net/browse/IMN-36?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
This PR implements API POST `/agreements/:agreementId/suspend`
Here's the link to the [corresponding function in the Scala codebase](https://github.com/pagopa/interop-be-agreement-process/blob/ef2615d5eef833c35fd0ef07affc092625b874cc/src/main/scala/it/pagopa/interop/agreementprocess/api/impl/AgreementApiServiceImpl.scala#L171)
* It creates a utility to create stamps in the right way, avoiding more issues like the one discussed here: https://github.com/pagopa/interop-be-monorepo/pull/136#discussion_r1439575894
* It fixes some logs to make them consistent with what the Scala codebase did …

IMN 36 - POST Agreement suspend

---

packages/agreement-process/open-api/agreement-service-spec.yml
packages/agreement-process/src/model/domain/errors.ts
packages/agreement-process/src/model/domain/validators.ts
packages/agreement-process/src/routers/AgreementRouter.ts
packages/agreement-process/src/services/agreementActivationProcessor.ts
packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/services/agreementStateProcessor.ts
packages/agreement-process/src/services/agreementSubmissionProcessor.ts
packages/agreement-process/src/utilities/errorMappers.ts
packages/models/src/agreement/agreement.ts

Close [IMN-32](https://pagopa.atlassian.net/browse/IMN-32?atlOrigin=eyJpIjoiZDI2NjVkYzdkZGI0NGM2NGE1OGUxMTM0NGI5MzhiMjciLCJwIjoiaiJ9)
This PR implements agreement `activation` API in agreement-service.
Tested E2E locally.
**Test steps** 
- create a valid descriptor in relative agreement's Eservice
- create agreement and set to state PENDING
- create two different tenant producer and consumer
[IMN-32]: https://pagopa.atlassian.net/browse/IMN-32?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-32 post agreement activate

---

packages/agreement-process/src/services/agreementService.ts

Closes [IMN-174](https://pagopa.atlassian.net/browse/IMN-174)
Closes [IMN-179](https://pagopa.atlassian.net/browse/IMN-179)
While working on #140 and reviewing the logic of other functions involving agreement upgrades, I noticed that both `upgradeAgreement` and `cloneAgreement` reused the `createAgreementLogic` function, which **does not** copy in the new agreement any of the following properties:   `verifiedAttributes`, `certifiedAttributes`, `declaredAttributes`, `consumerNotes`
However, looking at the Scala code, I understand that:
* `upgrade` shall copy in the new agreement all four properties (when it creates a new draft Agreement) - see [here](https://github.com/pagopa/interop-be-agreement-process/blob/ef2615d5eef833c35fd0ef07affc092625b874cc/src/main/scala/it/pagopa/interop/agreemen …

IMN-174 + IMN-179 - Logic fixes for agreement clone and create

---

packages/agreement-process/src/model/domain/models.ts
packages/agreement-process/src/model/domain/validators.ts
packages/agreement-process/src/services/agreementActivationProcessor.ts
packages/agreement-process/src/services/agreementContractBuilder.ts
packages/agreement-process/src/services/agreementSubmissionProcessor.ts
packages/agreement-process/src/services/agreementSuspensionProcessor.ts
packages/agreement-process/src/services/pdfGenerator.ts
packages/models/src/agreement/agreement.ts

All the attributes match the ones in the descriptor & consumer, so they are all copied

Improving Agreement attribute specific types

---

packages/agreement-process/src/services/readmodel/readModelService.ts

Closes [IMN-167](https://pagopa.atlassian.net/browse/IMN-167)
* The `getAgreements` function called inside `getAllAgreements` was not used anywhere else: the exposed `getAgreements` functionality is implemented without relying on it and has a different aggregation logic. I removed the function and reimplemented `getAllAgreements` in a simpler way
* Now, after this PR, `getAllAgreements` gets all agreements in one shot instead of doing one query per page of Agreements and then concatenating them
[IMN-167]: https://pagopa.atlassian.net/browse/IMN-167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refactoring getAllAgreements

---

packages/agreement-process/src/model/domain/errors.ts
packages/agreement-process/src/model/domain/validators.ts
packages/agreement-process/src/routers/AgreementRouter.ts
packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/services/readmodel/readModelService.ts
packages/agreement-readmodel-writer/src/model/converter.ts
packages/catalog-process/src/model/domain/errors.ts
packages/catalog-process/src/model/domain/models.ts
packages/catalog-process/src/model/domain/toEvent.ts
packages/catalog-process/src/routers/EServiceRouter.ts
packages/catalog-process/src/services/catalogService.ts
packages/catalog-process/src/services/readModelService.ts
packages/catalog-process/test/catalogService.test.ts
packages/catalog-process/test/db.test.ts
packages/catalog-process/test/utils.ts
packages/catalog-readmodel-writer/src/model/converter.ts
packages/models/src/agreement/agreement.ts
packages/models/src/brandedIds.ts
packages/models/src/eservice/eservice.ts
packages/tenant-process/src/model/domain/errors.ts

This PR introduces the EServiceId and EServiceDocumentId branded types.
Other IDs should be changed into branded type but we decided to split these refactors into multiple PRs.

IMN-166 Refactor Branded type - Pt2

---

packages/agreement-process/src/services/agreementActivationProcessor.ts
packages/agreement-process/src/services/agreementService.ts
packages/catalog-process/src/model/types.ts
packages/catalog-process/src/routers/EServiceRouter.ts
packages/catalog-process/src/services/catalogService.ts
packages/catalog-process/src/services/readModelService.ts
packages/catalog-process/src/utilities/errorMappers.ts

First PR to close [IMN-241](https://pagopa.atlassian.net/browse/IMN-241). 
**The same should then be done for `tenant` and `attribute-registry`.**
After this PR:
1. Operational logs correspond to the ones in the Scala codebase
2. Operational logs are performed at the beginning of each operation in `*Service.ts` modules (`catalogService`, `agreementService`)
For point 2, I had to perform a few small refactors: in the Catalog Router, some operations were calling `catalogService`, while some others were directly calling `readModelService` - I made all calls pass by the `catalogService`.
[IMN-241]: https://pagopa.atlassian.net/browse/IMN-241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Operational logs consistency - Part 1 - Agreement and Catalog

---

packages/catalog-process/open-api/catalog-service-spec.yml
packages/catalog-process/src/model/types.ts
packages/catalog-process/src/routers/EServiceRouter.ts
packages/catalog-process/src/services/catalogService.ts
packages/catalog-process/src/services/readModelService.ts
packages/catalog-process/test/catalogService.integration.test.ts
packages/catalog-process/test/utils.ts
packages/models/src/eservice/eservice.ts

[to be merged after #156]
Closes [IMN-212](https://pagopa.atlassian.net/browse/IMN-212)
[IMN-212]: https://pagopa.atlassian.net/browse/IMN-212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-212 - Add attributesIds filter to GET /eservices

---

packages/catalog-readmodel-writer/src/consumerService.ts

Closes [IMN-268](https://pagopa.atlassian.net/browse/IMN-268)
The issues were happening for two reasons:
1. both UPDATE and DELETE are implemented using more than one subsequent MongoDB `updateOne` operations. With the first operation updating the version to the new `msg.version` and the second operation using the same filter `"metadata.version": { $lt: msg.version }`, the second operation was not being executed.
2. one of the `arrayFilters` was causing an error as shown in the Jira card: being a filter on two different top-level fields, it must be separated into two different filters
Manually tested.
[IMN-268]: https://pagopa.atlassian.net/browse/IMN-268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-268 - Fixing readmodel writer DELETE & UPDATE Descriptor document

---

packages/catalog-process/src/services/readModelService.ts

Closes [IMN-269](https://pagopa.atlassian.net/browse/IMN-269)
✅ Automated test `should include eservices with no descriptors (requester is the producer, admin)` now works
✅ Manual test: GET /eservices now returns also EServices without Descriptors:
[IMN-269]: https://pagopa.atlassian.net/browse/IMN-269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-269 - GET /eservice - Adding descriptors filter only if corresponding params are present

---

packages/agreement-process/.env
packages/agreement-process/aws.config.local
packages/catalog-process/.env
packages/catalog-process/aws.config.local
packages/catalog-process/test/catalogService.integration.test.ts
packages/commons-test/aws.config.local
packages/commons-test/test/fileManager.test.ts
packages/commons/src/config/fileManagerConfig.ts
packages/commons/src/fileManager.ts

**Before**
**After**  -- doc is correctly deleted meaning the integration is working

IMN 270 - Proposal to use AWS CLI internals and env var instead of custom logic to override local AWS config

---

packages/catalog-process/open-api/catalog-service-spec.yml
packages/catalog-process/src/model/domain/apiConverter.ts
packages/catalog-process/src/model/domain/errors.ts
packages/catalog-process/src/model/domain/models.ts
packages/catalog-process/src/model/domain/toEvent.ts
packages/catalog-process/src/services/catalogService.ts
packages/catalog-process/src/utilities/errorMappers.ts
packages/catalog-process/test/catalogService.integration.test.ts
packages/catalog-process/test/utils.ts
packages/catalog-readmodel-writer/src/model/converterV1.ts
packages/catalog-readmodel-writer/src/model/converterV2.ts
packages/catalog-readmodel-writer/test/catalog-readmodel-writer.integration.test.ts
packages/models/proto/v1/eservice/eservice.proto
packages/models/proto/v2/eservice/eservice.proto
packages/models/src/brandedIds.ts
packages/models/src/eservice/eservice.ts

Closes [IMN-247](https://pagopa.atlassian.net/browse/IMN-247)
[IMN-247]: https://pagopa.atlassian.net/browse/IMN-247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-247 - EService Risk Analysis - adding new fields + updating createAgreement

---

packages/agreement-process/src/model/domain/validators.ts
packages/agreement-process/src/services/agreementActivationProcessor.ts
packages/agreement-process/src/services/agreementContractBuilder.ts
packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/services/agreementSubmissionProcessor.ts
packages/agreement-process/src/services/agreementSuspensionProcessor.ts
packages/agreement-process/src/services/pdfGenerator.ts
packages/agreement-process/src/services/readmodel/agreementQuery.ts
packages/agreement-process/src/services/readmodel/readModelService.ts
packages/catalog-process/src/model/domain/apiConverter.ts
packages/catalog-process/src/model/domain/errors.ts
packages/catalog-process/src/model/domain/toEvent.ts
packages/catalog-process/src/routers/EServiceRouter.ts
packages/catalog-process/src/services/catalogService.ts
packages/catalog-process/src/services/readModelService.ts
packages/catalog-process/test/catalogService.integration.test.ts
packages/catalog-process/test/utils.ts
packages/catalog-readmodel-writer/src/consumerServiceV1.ts
packages/catalog-readmodel-writer/test/catalog-readmodel-writer.integration.test.ts
packages/models/proto/v1/eservice/events.proto
packages/models/src/agreement/agreement.ts

This super low-priority PR renames every occurrence of `eService` into `eservice`.
I also renamed the field in the protobuf message, it shouldn't be a problem because protobuf internally uses the index and not the field name.
Some renaming are not included in this PR (primary error codes and some function names that should be changed) and will be changed in a future PR.

EService renaming

---

packages/catalog-process/src/utilities/versionGenerator.ts
packages/catalog-process/test/catalogService.integration.test.ts

This pull request is for fixing the numbering of new descriptors.
It seems every new descriptor was being numbered `"1"` because of a bug in the version generator.

IMN-312 Fix descriptors versions numbering in catalog-process

---

packages/catalog-process/src/model/domain/models.ts
packages/catalog-process/src/routers/EServiceRouter.ts
packages/catalog-process/src/services/catalogService.ts
packages/catalog-process/src/utilities/errorMappers.ts
packages/catalog-process/test/catalogService.integration.test.ts

This pull request is for fixing a bug related to the assignment of the `attributes` during the `updateDraftDescriptor` operation. We were just not assigning attributes at all in that endpoint.
The implementation include a refactor to reuse the code that performs the same actions during the `createDescriptor` operation.

IMN-314 Assign attributes during updateDraftDescriptor in catalog-process

---

packages/catalog-process/src/model/domain/toEvent.ts
packages/catalog-process/src/services/catalogService.ts
packages/catalog-process/test/catalogService.integration.test.ts
packages/catalog-readmodel-writer/src/consumerServiceV2.ts
packages/models/proto/v2/eservice/events.proto
packages/models/src/eservice/eserviceEvents.ts

This pull request is for adding minor changes related to events v2:
- the `archiveDescription` operation was generating an `EServiceDescriptorActivated` event. This bug was unintendedly added [here](https://github.com/pagopa/interop-be-monorepo/pull/207/files#diff-77a5bad1f3b877e7bfc968a9b423c16649fca358d54286d743fe34fa555564ceR1516)
- the `updateDraftDescriptor` operation was generating a `DraftEServiceUpdated` event, even though we do have an `EServiceDraftDescriptorUpdated` event
- the `updateDescriptor` operation was generating a `DraftEServiceUpdated` event, so I added a new `EServiceDescriptorQuotasUpdated` event. I forgot to add the event during the implementation of that new endpoint [here](https://github.com/pagopa/interop-be-monorepo/pull/216/files#diff-77a5bad1f3b877e7bfc968a9b4 …

IMN-176 Fix events v2 in catalog-process

---

packages/catalog-process/open-api/catalog-service-spec.yml
packages/catalog-process/src/model/domain/errors.ts
packages/catalog-process/src/model/domain/toEvent.ts
packages/catalog-process/src/routers/EServiceRouter.ts
packages/catalog-process/src/services/catalogService.ts
packages/catalog-process/src/utilities/errorMappers.ts
packages/catalog-process/test/catalogService.integration.test.ts
packages/catalog-readmodel-writer/src/consumerServiceV1.ts
packages/catalog-readmodel-writer/src/consumerServiceV2.ts
packages/commons/src/risk-analysis/models.ts
packages/models/proto/v1/eservice/events.proto
packages/models/proto/v2/eservice/events.proto
packages/models/src/eservice/eserviceEvents.ts

Closes [IMN-250](https://pagopa.atlassian.net/browse/IMN-250)
[IMN-250]: https://pagopa.atlassian.net/browse/IMN-250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN 250 - add Risk Analysis update endpoint in catalog process

---

packages/models/src/agreement/agreement.ts
packages/models/src/tenant/tenant.ts
packages/models/src/user/user.ts

This pull request is for using `z.coerce.date()` instead of `z.date()` in models definitions.

IMN-359 Add coerce to dates in model

---

packages/models/src/tenant/tenant.ts
packages/tenant-process/src/model/domain/apiConverter.ts
packages/tenant-process/src/model/domain/toEvent.ts
packages/tenant-process/src/services/validators.ts
packages/tenant-readmodel-writer/src/model/converter.ts

This pull request is for changing the type of the attributes of a tenant. This change is required to read tenants that are already in readmodel (as we are doing in `catalog-process`).
To keep the change simple, for now we will be also writing tenants in readmodel with the "older" labels.

IMN-361 Adjust tenant attributes type in models and tenant packages

---

packages/attribute-registry-process/src/services/attributeRegistryService.ts
packages/attribute-registry-process/test/attributeRegistryService.integration.test.ts
packages/commons/src/auth/authenticationMiddleware.ts
packages/models/proto/v1/tenant/tenant.proto
packages/models/src/tenant/protobufConverter.ts
packages/models/src/tenant/tenant.ts
packages/tenant-process/open-api/tenant-service-spec.yml
packages/tenant-process/src/model/domain/apiConverter.ts
packages/tenant-process/src/model/domain/toEvent.ts

This pull request is for adjusting the definition of a `tenant` both in models and in the protobuf definition (most of the changes are due to recent updates in the Scala implementation). The error during the riskAnalysis creation might arise from the unsuccessful parsing of a tenant in `catalog-process`.
Changes:
- the tenant feature is `PersistentCertifier` and not `Certifier`
- tenants have an optional `onboardedAt`
- tenants have an optional `subUnitType` (`AOO` or `UO`)
- tenants `mails` have an `id`
- tenants mail kind can also be `DIGITAL_ADDRESS`

IMN-378 Adjust tenant definition to fix riskAnalysis creation in catalog-process

---

packages/agreement-process/Dockerfile
packages/agreement-readmodel-writer/Dockerfile
packages/attribute-registry-process/Dockerfile
packages/attribute-registry-readmodel-writer/Dockerfile
packages/catalog-process/Dockerfile
packages/catalog-readmodel-writer/Dockerfile
packages/tenant-process/Dockerfile
packages/tenant-readmodel-writer/Dockerfile

Modify and merge after [IMN-161](https://github.com/pagopa/interop-be-monorepo/pull/161)
Closes [IMN-373](https://pagopa.atlassian.net/browse/IMN-373)
Related [IMN-73](https://pagopa.atlassian.net/browse/IMN-73)
[IMN-373]: https://pagopa.atlassian.net/browse/IMN-373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IMN-73]: https://pagopa.atlassian.net/browse/IMN-73?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Without changing the code I generated the catalog-process image twice using `--no-cache --build-arg SOURCE_DATE_EPOCH=0` obtaining the same hash `sha256:892b6e48a9c073bbfa58c4c2e8b5abc21243357a119cbaa2e3cc04cb11080c51`
[IMN-161]: https://pagopa.atlassian.net/browse/IMN-161?atlOrigin=eyJpIjoiNW …

IMN 373 - Multistep docker build

---

packages/tenant-process/test/tenant.integration.test.ts
packages/tenant-process/test/utils.ts

Doing what I did in https://github.com/pagopa/interop-be-monorepo/pull/284 also for `tenant-process`.
Tests pass ✅

Reusing commons-test utilities in tenant-process tests and fixing TS errors

---

packages/agreement-readmodel-writer/src/index.ts
packages/attribute-registry-readmodel-writer/src/index.ts
packages/authorization-updater/src/authorizationService.ts
packages/authorization-updater/src/index.ts
packages/catalog-readmodel-writer/src/consumerServiceV2.ts
packages/catalog-readmodel-writer/src/index.ts
packages/commons/src/auth/headers.ts
packages/commons/src/context/context.ts
packages/commons/src/logging/loggerMiddleware.ts
packages/commons/src/repositories/EventRepository.ts
packages/commons/src/repositories/sql/insertEvent.sql
packages/models/src/events/events.ts
packages/tenant-readmodel-writer/src/index.ts

Closes [IMN-301](https://pagopa.atlassian.net/browse/IMN-301)
In this PR I have partially reverted the changes done in IMN-300. The `correlationId` is now retrieved from the context using the `getContext` function just before saving the event in the event store.
[IMN-301]: https://pagopa.atlassian.net/browse/IMN-301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

 IMN 301 - Add details in consumer logs

---

register-connector-postgres.json

Closes [IMN-147](https://pagopa.atlassian.net/browse/IMN-147)
By default, Debezium uses the Postgres table primary key as kafka message primary key. For this reason, until now our kafka messages show `sequence_num` as key.
Kafka uses this key to select the correct partition for a message if a target partition is not specified. We tell Debezium to use a custom route to select the correct partition for a message so each message is routed to a specific partition.
This change sets the `stream_id` as Kafka message key. Now the `stream_id` will be used as a fallback value to decide which partition to route a message.
[IMN-147]: https://pagopa.atlassian.net/browse/IMN-147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN 147 - Kafka primary key

---

packages/commons/src/context/context.ts
packages/commons/src/logging/loggerMiddleware.ts
packages/models/src/events/events.ts

This PR changes the decoder for the `correlation_id` field of a kafka message from `.optional()` to `.nullish()` to handle `null` value cases

Fix kafka message decoder

---

renovate.json

With `autodiscover` set to `true`, Renovate runs on all the repositories it can access with the specified token. 
See the last run here and the screenshot below: https://github.com/pagopa/interop-be-monorepo/actions/runs/8552520446/job/23433780991
**🚨 I stopped it as soon as I saw the repositories discovered, so it should not have created any issues/PRs on other repos.**
---
I would keep the `repositories` setting even if it gives the following warning when running - in the future, this will be solved when Renovate is set up for the whole organization.

Renovate - removing autodiscover and setting specific repo

---

packages/agreement-process/test/agreementService.integration.test.ts
packages/commons-test/src/testUtils.ts

[ To be merged after #324 ]
Closes [IMN-218](https://pagopa.atlassian.net/browse/IMN-218)
---
---
---
[IMN-218]: https://pagopa.atlassian.net/browse/IMN-218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN 218 - Adding tests for get agreement producers and consumers

---

packages/notifier-seeder/src/models/catalogItemEventNotificationMessage.ts

Fix Event Kind type mapping during message conversion conversion in notifier-seeder.
Event Type `DraftEServiceUpdated` now using `catalog_item_updated`
Event Type `EServiceDraftDescriptorDeleted` now using `catalog_item_with_descriptors_deleted`
Event Type `EServiceDraftDescriptorUpdated` now usng `catalog_item_descriptor_updated`

Fix event kind for notificatoin message

---

packages/agreement-process/src/app.ts
packages/agreement-readmodel-writer/src/index.ts
packages/attribute-registry-process/src/app.ts
packages/attribute-registry-readmodel-writer/src/index.ts
packages/authorization-updater/src/index.ts
packages/catalog-process/src/app.ts
packages/catalog-readmodel-writer/src/index.ts
packages/commons/src/context/context.ts
packages/notifier-seeder/src/index.ts
packages/purpose-process/src/app.ts
packages/tenant-process/src/app.ts
packages/tenant-readmodel-writer/src/index.ts

Closes [IMN-473](https://pagopa.atlassian.net/browse/IMN-473)
Manually tested locally. The asyc local storage works as before and the correlation id is correctly stored in the database and used by the readmodel-writer. 
More tests should by done on a "real" environment to better check if the concurrency problem is resolved.
[IMN-473]: https://pagopa.atlassian.net/browse/IMN-473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN 473 - Fix global storage usage

---

packages/agreement-process/test/agreementService.integration.test.ts
packages/agreement-process/test/testAgreementConsumerDocuments.ts

[ To be merged after #328 ]
Closes [IMN-225](https://pagopa.atlassian.net/browse/IMN-225)
[IMN-225]: https://pagopa.atlassian.net/browse/IMN-225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-225 - adding tests for GET agreement consumer document

---

package.json

The lib `@protobuf-ts/protoc` always uses the latest version of the `protoc`, in order to avoid breaking change we pin the version in the `package.json`

Pin protoc version

---

packages/agreement-process/.env
packages/agreement-process/src/utilities/config.ts
packages/agreement-readmodel-writer/.env
packages/attribute-registry-process/.env
packages/attribute-registry-process/src/utilities/config.ts
packages/attribute-registry-readmodel-writer/.env
packages/authorization-updater/.env
packages/catalog-process/.env
packages/catalog-process/src/utilities/config.ts
packages/catalog-readmodel-writer/.env
packages/commons/src/auth/jwt.ts
packages/commons/src/config/commonConfig.ts
packages/purpose-process/.env
packages/purpose-process/src/utilities/config.ts
packages/tenant-process/.env
packages/tenant-process/src/utilities/config.ts
packages/tenant-readmodel-writer/.env

Closes [IMN-480](https://pagopa.atlassian.net/browse/IMN-480)
This PR:
* adds audience validation to JWT token verify
* removes unneeded HTTP/JWT config vars from services that don't need them
Changing valid audiences in `.env`:
Getting `401 Unauthorized`:
[IMN-480]: https://pagopa.atlassian.net/browse/IMN-480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-480 - Validating aud in JWT

---

packages/commons-test/src/eventStoreTestUtils.ts

Re-introducing event store schema checks after #444, only as a test utility for event store test functions, to avoid issues such as https://github.com/pagopa/interop-be-monorepo/pull/377#discussion_r1567590890

Reenabling event store schema enum for tests

---

packages/agreement-process/src/routers/AgreementRouter.ts
packages/attribute-registry-process/src/routers/AttributeRouter.ts
packages/catalog-process/src/routers/EServiceRouter.ts
packages/commons/package.json
packages/commons/src/auth/authorizationMiddleware.ts
packages/commons/src/index.ts
packages/commons/src/router/zodiosValidationErrorHandler.ts
packages/models/src/errors.ts
packages/purpose-process/src/routers/PurposeRouter.ts
packages/tenant-process/src/routers/TenantRouter.ts
pnpm-lock.yaml

Closes [IMN-475](https://pagopa.atlassian.net/browse/IMN-475)
This PR adds a custom `zodios` error handler that converts zod validation errors into API problems with code `400 bad request`. In this way, in case of missing or bad query parameters/body in requests, the error response follows the API problems standard used by other error responses.
Run some smoke tests on different requests.
--- 
To test that errors different from this new bad request error are still working as expected.
[IMN-475]: https://pagopa.atlassian.net/browse/IMN-475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-475 - Adding custom error handler for zodios validation errors

---

packages/notifier-seeder/src/models/catalogItemEventNotification.ts
packages/notifier-seeder/src/models/catalogItemEventNotificationConverter.ts

Close [IMN-485](https://pagopa.atlassian.net/browse/IMN-485)
This PR introduce catalog notification types used by Notification-seeder service when handle catalog item event and publish to the SQS queue.  
The types are used during the notification's creation in `toCatalogItemEventNotification` methods
✅ Integration test "Update Descriptor Event Message" successed
[IMN-485]: https://pagopa.atlassian.net/browse/IMN-485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add types to Catalog Item Notifications

---

packages/commons-test/test/jwt.unit.test.ts

The test was checking `sub` as a required claim, but actually `sub` is the only standard claim not present in all cases: it is not present in interop UI tokens.

Fixing commons tests JWT flaky test

---

packages/agreement-process/src/app.ts
packages/agreement-process/src/routers/AgreementRouter.ts
packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/services/agreementSubmissionProcessor.ts
packages/agreement-readmodel-writer/src/index.ts
packages/attribute-registry-process/src/app.ts
packages/attribute-registry-readmodel-writer/src/index.ts
packages/authorization-updater/src/authorizationService.ts
packages/authorization-updater/src/index.ts
packages/catalog-process/src/app.ts
packages/catalog-readmodel-writer/src/index.ts
packages/commons/src/auth/authenticationMiddleware.ts
packages/commons/src/auth/headers.ts
packages/commons/src/context/context.ts
packages/commons/src/logging/index.ts
packages/commons/src/logging/loggerContext.ts
packages/commons/src/logging/loggerMiddleware.ts
packages/notifier-seeder/src/index.ts
packages/purpose-process/src/app.ts
packages/purpose-readmodel-writer/src/index.ts
packages/tenant-process/src/app.ts
packages/tenant-readmodel-writer/src/index.ts

Closes [IMN-487](https://pagopa.atlassian.net/browse/IMN-487)
**Note:**
* This PR also adds the service name to every log; at the moment, it was being logged only in express-winston logs performed by the logger middleware, but not in other logs
[IMN-487]: https://pagopa.atlassian.net/browse/IMN-487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-487 - always log correlation id

---

docker/docker-compose.yml

See docs: https://github.com/mongo-express/mongo-express
* log in now works with `root` `example` on the local Mongo express 
* smoke tested some API calls to process + readmodel writes, still working correctly

Fixing mongo express local dev credentials

---

packages/agreement-process/src/utilities/config.ts
packages/agreement-process/test/utils.ts
packages/attribute-registry-process/test/utils.ts
packages/catalog-process/src/utilities/config.ts
packages/commons-test/src/containerTestUtils.ts
packages/commons-test/src/setupTestContainersVitest.ts
packages/commons-test/src/setupTestContainersVitestGlobal.ts
packages/commons/src/config/fileManagerConfig.ts
packages/eservice-descriptors-archiver/test/eserviceDescriptorsArchiver.integration.test.ts
packages/eservice-descriptors-archiver/test/utils.ts
packages/eservice-descriptors-archiver/test/vitestGlobalSetup.ts
packages/eservice-descriptors-archiver/vitest.config.ts
pnpm-lock.yaml

This PR closes [IMN-536](https://pagopa.atlassian.net/browse/IMN-536) only for the `eservices-descritptors-archiver` service, if the approach makes sense I will port it also to all other services.
[IMN-536]: https://pagopa.atlassian.net/browse/IMN-536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Reusing vitest global setup in EServices Descriptor Archiver

---

packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/services/agreementSubmissionProcessor.ts

This PR fix contract creation during Agreement `submit` the contract is created and uploaded to S3 only when is the first activation.

Fix: submit agreement create contract only during first activation

---

packages/agreement-process/src/services/agreementActivationProcessor.ts
packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/services/agreementStateProcessor.ts
packages/agreement-process/src/services/agreementSubmissionProcessor.ts
packages/agreement-process/src/services/agreementSuspensionProcessor.ts
packages/agreement-process/test/suspendAgreement.test.ts
packages/commons/src/repositories/EventRepository.ts

Closes [IMN-590](https://pagopa.atlassian.net/browse/IMN-590)
In this PR I re-added the update of the `suspendedByPlatform` in activation and submission, and its usage in calculating the next state (also for suspension) - all things removed in #296. Not updating the flag could potentially lead to inconsistent Agreement states. For example: in the activation, the result could be an `Active` agreement with the `suspendedByPlatform` flag set to true but without writing a corresponding SuspendByPlatform event
Since we now update the flag in activate and submit, I also added the corresponding events.
[IMN-590]: https://pagopa.atlassian.net/browse/IMN-590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
See corresponding automated tests being …

IMN-590 - Fixing suspendedByPlatform flag inconsistencies

---

packages/agreement-process/src/services/agreementActivationProcessor.ts
packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/services/agreementSubmissionProcessor.ts

Closes [IMN-600](https://pagopa.atlassian.net/browse/IMN-600)
See automated tests in #567, based on this one.
[IMN-600]: https://pagopa.atlassian.net/browse/IMN-600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-600 - Fixing return value for activate agreement

---

.npmrc
packages/agreement-process/package.json
packages/agreement-readmodel-writer/package.json
packages/commons-test/package.json
packages/commons/package.json
packages/eservice-descriptors-archiver/package.json
pnpm-lock.yaml

Closes [IMN-504](https://pagopa.atlassian.net/browse/IMN-504)
[IMN-504]: https://pagopa.atlassian.net/browse/IMN-504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
We still have warnings on the TS version because `@pagopa/eslint-config` uses an old version of `eslint-plugin-functional` that has `typescript` as a peer dependency. Updating it should fix the issue.

IMN-504 - pnpm stricter peer dependencies

---

turbo.json

This PR introduces the turbo configuration UI into the project configuration, simplifying the use with old UI without needing additional environment variables or parameters when launching tasks.Very effectful when there isn't enough space to display the shell, the old configuration works well. In my opinion, the old UI is more readable and intuitive.

Add default config turbo ui as stream

---

.eslintrc.cjs
package.json
tsconfig.eslint.json

`typescript-eslint` docs suggest two different ways to configure it on a monorepo: https://typescript-eslint.io/getting-started/typed-linting/monorepos
1. One root tsconfig.json
2. One tsconfig.json per package 
We were using approach 2 which can result in out-of-memory errors. Citing [this chapter](https://typescript-eslint.io/getting-started/typed-linting/monorepos#important-note-regarding-large--10-multi-package-monorepos
) of the docs: "We've had reports that for sufficiently large and/or interdependent projects, you may run into OOMs using this approach".
Switching to approach 1 solves our linter issues and speeds up the linter 2x.
See also:
- https://github.com/typescript-eslint/typescript-eslint/issues/1192#issuecomment-565286938
- …

Linter fix - switching to single TSConfig approach for typescript-eslint configuration

---

packages/authorization-process/Dockerfile
packages/authorization-process/package.json
packages/client-readmodel-writer/Dockerfile
packages/client-readmodel-writer/package.json
packages/key-readmodel-writer/Dockerfile
packages/key-readmodel-writer/package.json
pnpm-lock.yaml

New merged packages did not update dependencies from `main` in the respective PRs. I'm doing it here to avoid having misalignment of versions between packages.

Bringing auth-process, client, and key deps up to date

---

packages/agreement-email-sender/package.json
pnpm-lock.yaml

This FIX allows copying of HTML resource files during build task for email sender service.

Fix missing resources files during email sender

---

renovate.json

We did not have auto-merge enabled for PRs that merely update the digest of a Docker image.
This caused PRs like the following to wait for manual merge thus blocking Renovate automatic updates for days if not manually merged:
- https://github.com/pagopa/interop-be-monorepo/pull/680
- https://github.com/pagopa/interop-be-monorepo/pull/683
This PR adds a config to enable auto-merge of digest updates.
See: https://docs.renovatebot.com/docker/#automerge-digest-updates

Adding automergeDigest to Renovate config

---

pnpm-lock.yaml

In #698 the PNPM lock file was erroneously updated to `lockfileVersion: '9.0'` because `pnpm i` was run with PNPM version 9, while at the moment we still use version 8 for this project: https://github.com/pagopa/interop-be-monorepo/blob/c26e4621e87c2f7db4f0d5e301f24c354663f64c/package.json#L46
Migrating to version 9 requires some work - let's stick with version 8 for now.
I ran `pnpm i` with pnpm version 8 locally and the lock file was downgraded as expected.
This is now the diff with commit `f7068b01`: the last commit on `main` before the merge of #698.

Fixing pnpm lockfile to fix build

---

packages/agreement-process/Dockerfile

On `main`, the build fails due to a wrong path referenced in the Dockerfile: https://github.com/pagopa/interop-be-monorepo/actions/runs/9853743986/job/27204950380
This PR fixes the error.

Fixing agreement process build

---

packages/eservice-descriptors-archiver/Dockerfile

In the changes related to #710 I forgot to remove the copy of the catalog service open API specs.

Fix eservice archiver Docker Image

---

packages/authorization-process/package.json
packages/authorization-process/src/model/domain/apiConverter.ts
packages/authorization-process/src/routers/AuthorizationRouter.ts

This PR is for fixing the following wrong response on `getClientWithKeys`:
`2024-07-18 13:51:09.228 WARN [it.pagopa.interop.backendforfrontend.service.impl.AuthorizationProcessServiceImpl] - [UID=f07ddb8f-17f9-47d4-b31e-35d1ac10e521] [OID=e79a24cd-8edc-441e-ae8d-e87c3aea0059] [CID=f1f1d1b5-ce89-4c54-b0fe-e22e8cdb0758] Retrieving clients with keys FAILED. code > 200 - message > Unable to unmarshall content to [it.pagopa.interop.authorizationprocess.client.model.ClientsWithKeys] - response > Some({"results":[{"id":"66f3193f-5d2a-41b6-a4c9-6dea7e76d36a","name":"client-0-6172431924968498-1068392203566964","consumerId":"e79a24cd-8edc-441e-ae8d-e87c3aea0059","users":[],"createdAt":"2024-07-18T13:51:08.220Z","purposes":[],"kind":"CONSUMER","description":"Descrizione …

fixed error in clientConverter in authProcess

---

packages/catalog-process/src/utilities/errorMappers.ts

This pull request is for fixing the previous PR #762. The new error has not been added inside the error mapper, so it resulted in a `500` error code.

PIN-5129 Fix error mapper in publishDescriptor in catalog-process

---

packages/authorization-process/src/routers/AuthorizationRouter.ts

This pull request is for fixing the error mapper used in `addClientPurpose`.

IMN-55 Fix addClientPurpose error mapper in authorization-process

---

packages/catalog-process/src/model/domain/toEvent.ts
packages/catalog-process/src/services/catalogService.ts
packages/catalog-process/test/deleteDraftDescriptor.test.ts
packages/catalog-process/test/deleteEservice.test.ts

This pull request is for adjusting the `deleteEService` and `deleteDraftDescriptor` endpoints:
- in the former, the deletion of the descriptor has been added as a separate event
- in the latter, the deletion of the last (or only) descriptor should lead to the deletion of the entire eservice.

PIN-5153 Adjust deleteEService and deleteDraftDescriptor in catalog-process

---

packages/api-clients/open-api/authorizationManagementApi.yaml
packages/authorization-updater/src/authorizationService.ts
packages/authorization-updater/test/authorizationUpdater.test.ts

This PR should solve the problem of `authUpdater` that keeps restarting since there was an incorrect parameter being passed to the `createClient` of the `auth-Management`; its open api wasn't correct too and has been updated to reflect the one in Scala.
Thanks to @rGregnanin for pointing out the problem on the `createClient`

Fix for restarting authUpdater

---

packages/commons/src/config/kafkaConfig.ts
packages/commons/src/config/producerServiceConfig.ts
packages/kafka-iam-auth/src/index.ts

Currently MSK Serverless provides a single bootstrap host, but typical Kafka clusters provide multiple hosts.
This PR will fix KAFKA_BROKERS configuration to correctly parse comma-separated hosts.

fix: KAFKA_BROKERS value

---

packages/notifier-seeder/src/models/authorization/authorizationEventNotification.ts
packages/notifier-seeder/src/models/authorization/authorizationEventNotificationConverter.ts
packages/notifier-seeder/test/notificationMessage.integration.test.ts

This pull request is for fixing the handling of the `KeysAdded` event in `notification-seeder`

Fix auth notifier seeder

---

packages/models/src/tenant/protobufConverterFromV1.ts
packages/models/src/tenant/protobufConverterFromV2.ts
packages/models/src/tenant/protobufConverterToV2.ts
packages/tenant-readmodel-writer/test/converterV1.ts

Followup after #776 - some tenant model converters were stripping `revocationTimestamp` from tenant attributes. TS was not complaining because undefined is an acceptable value.
Bug found while testing #897

Tenant quick fix - Fixing revocation timestamp missing in tenant

---

packages/compute-agreements-consumer/src/converters.ts
packages/compute-agreements-consumer/src/index.ts

This PR fixes a crash due to an incorrect data conversion coming from the event.
A converter that converts the tenant event data structure to a tenant data structure compatible to the `computeAgreementsByAttribute` request body.

FIX `compute-agreement-consumer` crash on startup

---

packages/bff/src/model/api/tenantApiConverter.ts
packages/bff/src/routers/tenantRouter.ts
packages/bff/src/services/attributeService.ts
packages/bff/src/services/tenantService.ts
packages/commons/src/utils/arrays.ts

Based on #897 
2nd part of [IMN-607](https://pagopa.atlassian.net/browse/IMN-607)
This PR implements the following BFF Tenant methods:
- GET Certified Attributes
- GET Verified Attributes
- GET Declared Attributes
[IMN-607]: https://pagopa.atlassian.net/browse/IMN-607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN 607 - BFF Tenant router - Pt2

---

packages/bff/src/model/api/tenantApiConverter.ts
packages/bff/src/providers/clientProvider.ts
packages/bff/src/routers/tenantRouter.ts
packages/bff/src/services/tenantService.ts

Based on #934 
Last part of [IMN-607](https://pagopa.atlassian.net/browse/IMN-607)
This PR implements the following BFF tenant methods:
- Get tenant
- Get tenants
[IMN-607]: https://pagopa.atlassian.net/browse/IMN-607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-607 - BFF Tenant router - Pt4

---

packages/api-clients/src/apiGatewayApi.ts
packages/api-clients/src/index.ts
packages/api-clients/src/purposeApi.ts
packages/api-gateway/.env
packages/api-gateway/src/api/purposeApiConverter.ts
packages/api-gateway/src/clients/clientsProvider.ts
packages/api-gateway/src/config/config.ts
packages/api-gateway/src/models/errors.ts
packages/api-gateway/src/routers/apiGatewayRouter.ts
packages/api-gateway/src/services/agreementService.ts
packages/api-gateway/src/services/validators.ts
packages/api-gateway/src/utilities/arrays.ts
packages/purpose-process/.env

Based on #904 
Closes [IMN-745](https://pagopa.atlassian.net/browse/IMN-745)
With the same consumerId / eserviceId used for the purposes above.
This error  "bubbles up" from the agreement process API call response:
[IMN-745]: https://pagopa.atlassian.net/browse/IMN-745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-745 - API Gateway - GET Agreement Purposes

---

packages/bff/.env
packages/bff/src/config/config.ts
packages/bff/src/routers/catalogRouter.ts
packages/bff/src/services/catalogService.ts
packages/commons/src/file-manager/fileManager.ts

Part of [BFF Catalog Routes](https://pagopa.atlassian.net/browse/IMN-604)
Closes [IMN-740](https://pagopa.atlassian.net/browse/IMN-740)
Merge after [PR-882](https://github.com/pagopa/interop-be-monorepo/pull/882)
Implements `/import/eservices/presignedUrl` 
✅  Local test return response 200 with putSignedUrl and fileName
[IMN-740]: https://pagopa.atlassian.net/browse/IMN-740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-740 get import presigned url

---

packages/agreement-process/src/services/readModelService.ts
packages/bff/src/routers/agreementRouter.ts
packages/bff/src/routers/attributeRouter.ts
packages/bff/src/routers/authorizationRouter.ts
packages/bff/src/routers/catalogRouter.ts
packages/bff/src/routers/clientRouter.ts
packages/bff/src/routers/privacyNoticeRouter.ts
packages/bff/src/routers/producerKeychainRouter.ts
packages/bff/src/routers/purposeRouter.ts
packages/bff/src/routers/selfcareRouter.ts
packages/bff/src/routers/supportRouter.ts
packages/bff/src/routers/tenantRouter.ts
packages/bff/src/services/attributeService.ts
packages/bff/src/services/authorizationService.ts
packages/bff/src/services/catalogService.ts
packages/bff/src/services/clientService.ts
packages/bff/src/services/producerKeychainService.ts
packages/bff/src/services/purposeService.ts
packages/bff/src/services/selfcareService.ts

This PR introduces a `Zod.parse` on every response of the BFF router.
This guarantees that we are not returning properties in excess to the client avoiding potential security issues or leaking of information.

IMN-819 parse responses

---

packages/api-clients/template-bff.hbs
packages/backend-for-frontend/src/routers/attributeRouter.ts

Close IMN-835
Fix how query params type array of attribute kind are processed by patch using bff-template.

IMN-835 - fix query params Attribute kinds array required in zodios patch

---

packages/backend-for-frontend/src/routers/producerKeychainRouter.ts

`JSON.stringify` could not serialize the `req` object and that led to the entire crash of the pod

Fix wrong `req` value serialization in error log

---

packages/backend-for-frontend/src/services/purposeService.ts

Closes [IMN-840](https://pagopa.atlassian.net/browse/IMN-840?atlOrigin=eyJpIjoiMTliZTBlNTA5MzQ3NDdjNWFjYzBmN2I5ODEyNzBmMjAiLCJwIjoiaiJ9)
Fix Purpose service returned type, Bff returns CreatedResource for endpoint `/purposes`
[IMN-840]: https://pagopa.atlassian.net/browse/IMN-840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-840 - Purpose service Fix returned type

---

packages/backend-for-frontend/src/api/attributeApiConverter.ts
packages/backend-for-frontend/src/services/attributeService.ts

The declared and verified attribute creation attribute process call does not need the `toApiAttributeProcessSeed` remapper.
The remapper in question was adding a `code` property which presence is not compatible with body the process calls was expecting.

IMN-838 - Fix attributes creation

---

packages/agreement-lifecycle/src/validator/attributesValidator.ts

The function `attributesSatisfied` used to check if all Eservice descriptor attributes are contained into Tenant attributes, 
using [Array.every()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every) 
that properly returns true if the array is empty ([example](https://www.typescriptlang.org/play/?#code/MYewdgzgLgBAhgJwQRgFzQQSzAcwNoC6MAvDIQNwBQloksUAptCfEsgHQMBuDCAngAoBAShIA+GFAQBXBsOq0IIADYN2ykDgGNowoA)). 
But it doesn't work properly with an array of empty array, eg:
```
[[],[]].every( predicate )
```
In some case array of empty array were saved into read model and it generate the BUG, `every` function doesn't works as expected with an array of empty array.
Filter empty array from provided list

IMN-839 Return false if certified attributes is empty

---

packages/backend-for-frontend/src/services/agreementService.ts
packages/commons/src/file-manager/fileManager.ts

Closes [IMN-863](https://pagopa.atlassian.net/browse/IMN-863)
1. Add a consumer document to an agreement
2. Try to retrieve it
3. Error (logs say the file cannot be found in the bucket at the specified path)
The same flow works - **the document must be re-added because the error was on the add, not on the retrieve.**
[IMN-863]: https://pagopa.atlassian.net/browse/IMN-863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-863 - Fixing Add Consumer Document path in BFF

---

packages/backend-for-frontend/src/services/purposeService.ts

Closes [IMN-870](https://pagopa.atlassian.net/browse/IMN-870)
Purpose created in the read model
[IMN-870]: https://pagopa.atlassian.net/browse/IMN-870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-870 - Fixing parsing error in /reverse/purposes

---

.github/workflows/build-push.yaml

The build on main is broken due to a typo in a package folder name after #973

Fixing main build after  #973

---

packages/api-gateway/src/app.ts
packages/backend-for-frontend/src/app.ts
packages/commons/src/auth/authenticationMiddleware.ts
packages/commons/src/auth/authorizationMiddleware.ts
packages/commons/src/auth/headers.ts
packages/commons/src/auth/jwt.ts
packages/commons/src/context/context.ts
packages/models/src/errors.ts

Closes [IMN-879](https://pagopa.atlassian.net/browse/IMN-879)
Closes [IMN-878](https://pagopa.atlassian.net/browse/IMN-878)
This PR separates the correlationId parsing from the authentication/authorization.
CorrelationId parsing was moved into the contextMiddleware, where it's also possible to specify that correlationId should not be read from headers but just generated in place.
It also fixes an issue in authentication that was causing `500` instead of `401` on invalid token.
[IMN-879]: https://pagopa.atlassian.net/browse/IMN-879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IMN-878]: https://pagopa.atlassian.net/browse/IMN-878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IMN-879 - Refactoring headers parsing and improving auth

---

packages/agreement-process/src/app.ts
packages/api-gateway/src/app.ts
packages/attribute-registry-process/src/app.ts
packages/authorization-process/src/app.ts
packages/backend-for-frontend/src/app.ts
packages/catalog-process/src/app.ts
packages/purpose-process/src/app.ts
packages/tenant-process/src/app.ts

Processes were failing on status for missing correlation id:

Handling health before any other middleware

---

packages/dtd-catalog-exporter/package.json

Closes [PIN-5566](https://pagopa.atlassian.net/browse/PIN-5566 )
Tested locally, docker container now runs correctly.
[PIN-5566]: https://pagopa.atlassian.net/browse/PIN-5566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN-5566 - fixing dtd catalog exporter docker run

---

packages/purpose-process/src/services/purposeService.ts
packages/purpose-process/src/services/readModelService.ts
packages/purpose-process/src/services/validators.ts
packages/purpose-process/test/activatePurposeVersion.test.ts
packages/purpose-process/test/getRiskAnalysisDocument.test.ts
packages/purpose-process/test/rejectPurposeVersion.test.ts
packages/purpose-process/test/suspendPurposeVersion.test.ts
packages/purpose-process/test/utils.ts

Closes [PIN-5509](https://pagopa.atlassian.net/browse/PIN-5509)
Closes [PIN-5510](https://pagopa.atlassian.net/browse/PIN-5510)
Closes [PIN-5511](https://pagopa.atlassian.net/browse/PIN-5511)
Closes [PIN-5512](https://pagopa.atlassian.net/browse/PIN-5512)
With this PR a delegate can also:
- Reject a new purpose version;
- Activate a new purpose version;
- Retrieve the purpose's risk analysis document;
- Suspend a purpose;
- Updated to return `PRODUCER` ownership if the requester is either the delegate or the producer.
- Added validation: Throws an error if the requester is the producer but an active delegation exists for the e-service.
- Introduced a new assertion, `assertRequesterIsProducer`, to validate requester roles:
- If the e-service has an active delegation, the requester must be …

PIN-5203 - Updated purpose process for producer delegations  

---

packages/api-gateway/.env
packages/api-gateway/src/clients/clientsProvider.ts
packages/api-gateway/src/config/config.ts
packages/api-gateway/src/models/errors.ts
packages/api-gateway/src/routers/apiGatewayRouter.ts
packages/api-gateway/src/services/purposeService.ts
packages/api-gateway/src/services/validators.ts

Closes [PIN-5605](https://pagopa.atlassian.net/browse/PIN-5605)
The only needed change I found in the `api-gateway` router was inside the `getPurpose` call, which allowed only the e-service producer or the consumer to access the purpose.
The change has been made to allow also the delegate to access it.
[PIN-5605]: https://pagopa.atlassian.net/browse/PIN-5605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN-5605 - Allow delegate to retrieve purpose in api-gateway

---

packages/agreement-process/src/model/domain/agreement-validators.ts
packages/agreement-process/src/model/domain/errors.ts
packages/agreement-process/src/resources/templates/documents/agreementContractTemplate.html
packages/agreement-process/src/routers/AgreementRouter.ts
packages/agreement-process/src/services/agreementContractBuilder.ts
packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/test/activateAgreement.test.ts
packages/agreement-process/test/agreementStatesFlows.test.ts
packages/agreement-process/test/submitAgreement.test.ts
packages/agreement-process/test/upgradeAgreement.test.ts
packages/agreement-process/test/utils.ts
packages/models/src/agreement/agreement.ts

Based on #1153 
This updates the new standard agreement template (the one without any delegation) to match the Figma template.
Manual test generated the following contract:
[69e2865e-65ab-4e48-a638-2037a9ee2ee7_69e2865e-65ab-4e48-a638-2037a9ee2ee7_20241125154756_agreement_contract.pdf](https://github.com/user-attachments/files/17904632/69e2865e-65ab-4e48-a638-2037a9ee2ee7_69e2865e-65ab-4e48-a638-2037a9ee2ee7_20241125154756_agreement_contract.pdf)

PIN-5737 - Implementing new agreement contract standard template

---

packages/api-clients/open-api/bffApi.yml
packages/backend-for-frontend/src/api/catalogApiConverter.ts
packages/backend-for-frontend/src/services/catalogService.ts

Closes [PIN-5558](https://pagopa.atlassian.net/browse/PIN-5558)
[PIN-5558]: https://pagopa.atlassian.net/browse/PIN-5558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN 5558 - Get eservice descriptor

---

packages/api-clients/open-api/bffApi.yml
packages/api-clients/open-api/catalogApi.yml
packages/backend-for-frontend/src/api/catalogApiConverter.ts
packages/backend-for-frontend/src/services/catalogService.ts
packages/catalog-process/src/model/domain/apiConverter.ts

- Updated BFF api's component `ProducerEServiceDescriptor`, adding `rejectionReasons` array;
- Updated `ProducerEService` data component, returned from `GET /producers/eservices`, added `requireCorrections` property.

Added `requireCorrections` and `rejectionReasons` in bff catalog apis

---

packages/agreement-outbound-writer/package.json
packages/api-clients/open-api/bffApi.yml
packages/backend-for-frontend/src/api/catalogApiConverter.ts
packages/catalog-outbound-writer/package.json
packages/purpose-outbound-writer/package.json
packages/tenant-outbound-writer/package.json
pnpm-lock.yaml

After merging `develop` into `feature/incaricato`  in 8fcf78f4a:
- outbound writers build was broken
- PNPM lock was not updated correctly, generating a big diff with `develop`
This PR fixes both issues.

Updating outbound models version and fixing PNPM lock after merge

---

packages/agreement-process/src/resources/templates/documents/agreementContractTemplate.html

Closes [PIN-5774](https://pagopa.atlassian.net/browse/PIN-5774)
This PR add missed info in agreement contract template when producer delegation is active.
[PIN-5774]: https://pagopa.atlassian.net/browse/PIN-5774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
----

Add missing delegation info in agreement template

---

packages/agreement-process/src/model/domain/agreement-validators.ts
packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/services/readModelService.ts
packages/agreement-process/test/activateAgreement.test.ts
packages/agreement-process/test/agreementConsumerDocuments.test.ts
packages/agreement-process/test/rejectAgreement.test.ts
packages/agreement-process/test/suspendAgreement.test.ts

In this PR I simplify agreement validators for cases where we must check if the caller is the producer or the delegate producer - this PR is needed on `feature/incaricato` since it simplifies our work in implementing the same logic also for consumer delegations.

Standardizing agreement requester validators

---

packages/backend-for-frontend/src/api/delegationApiConverter.ts

Fixed issue where the zod parsing of the response data was throwing a 500 error due to incorrect delegation doc parsing

Fix Delegation bff api parsing

---

packages/backend-for-frontend/src/services/catalogService.ts
packages/backend-for-frontend/src/services/validators.ts

Fixed an issue where `getProducerEServiceDescriptor` and `getProducerEServiceDetails` requester assertions were not taking into account producer delegations.
Added new `assertRequesterCanActAsProducer` assertion that checks whatever the requester is a direct producer or a delegated one.

Fix BFF e-service producer assertions

---

packages/delegation-process/src/routers/DelegationRouter.ts

Fixed an issue where the response data zod parsing of the delegation contract was failing.
Added the proper api converter.

Fix delegation contract api zod parsing error

---

packages/tenant-process/src/routers/TenantRouter.ts
packages/tenant-process/src/services/readModelService.ts
packages/tenant-process/src/services/tenantService.ts
packages/tenant-process/test/verifyVerifiedAttribute.test.ts

With this refactor we achieve the following:

Minor refactor on verifyVerifiedAttribute

---

packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/services/agreementStateProcessor.ts
packages/agreement-process/src/services/agreementSuspensionProcessor.ts
packages/agreement-process/test/upgradeAgreement.test.ts

When there are active delegations, the attribute checks shall happen only on the delegator tenant, not considering the 
attributes of the delegate.
The `nextState...` methods in the agreement service perform attribute checks and based on the initial/target state and attributes, choose the next state. Thus, they should not consider delegate tenants but only the original consumer and producer.
The current implementation **could** cause a bug, that can be reproduced as follows:
1. Tenant A delegates Tenant B as the producer
2. Tenant B creates an agreement for themself, not as the delegate of Tenant A, the draft agreement will have consumerId = Tenant B
3. Tenant B submits the agreement
4. nextStateFromDraft [checks also the delegateId](https://github.com/pagopa/interop-be-monorepo/pull/1260/ …

Removing delegation info from state processors

---

packages/purpose-process/src/services/purposeService.ts
packages/purpose-process/test/getPurposeById.test.ts

This PR makes the purpose risk analysis visible for the e-service active producer delegate.
Added a lot of tests that covers all the cases where the risk analysis is visible or not.

PIN-5818 - Fix purpose risk analysis visibility for producer delegate

---

packages/agreement-process/src/model/domain/agreement-validators.ts
packages/agreement-process/src/services/agreementContractBuilder.ts
packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/services/agreementUpgradeProcessor.ts
packages/agreement-process/src/services/readModelService.ts

This PR fixes an issue identified by @sandrotaje while implementing #1275.
Imagine Consumer C delegates delegate tenant D to consume Eservice E.
C tries to upgrade an existing agreement for E (same would apply to any other operation allowed by the consumer or delegate consumer)
C is not allowed to upgrade because there is an active delegation, and D shall operate instead of C.
The query as it was implemented before this fix was:
1. getting the active delegation with delegateId === to the caller tenant https://github.com/pagopa/interop-be-monorepo/pull/1274/files#diff-71db2d22095ae81787fc9ee7ffb2606a4a832b763fb13e3c5d19646434e3d951L753
2. In this case, the caller is C, so a delegation cannot be found, and the result is undefined (the delegation exists for the agreement but the delegate is …

Fixing agreement service delegate operations validators

---

packages/agreement-email-sender/src/index.ts

Fix wrong `email` value used for AWS SES service from env var configuration during Agreement Email Sender initialization.

Fix AWS SES email sender into Agreement Email Sender

---

packages/catalog-process/src/services/readModelService.ts
packages/catalog-process/test/getEservices.test.ts

This PR fixes an issue where the e-services with no descriptor or one in draft/waiting for approval was not visible for the delegate tenant

Fix `getEServices` visibility filter with producer delegation

---

packages/client-readmodel-writer/test/consumerServiceV1.test.ts
packages/client-readmodel-writer/test/consumerServiceV2.test.ts
packages/delegation-readmodel-writer/test/consumerServiceV2.test.ts
packages/producer-keychain-readmodel-writer/test/consumerServiceV2.test.ts
packages/tenant-readmodel-writer/test/consumerServiceV2.test.ts

In my opinion, this improves the code by:
- removing unused properties to prevent mistakes when creating a new test, as the object might otherwise have incorrect `type` and `data` properties
- make it more clear that, when adding a new test, the correct `type` and `data` should be added
This was already approved for the consumer service in #1228

Improve mockMessage type in tests

---

packages/agreement-process/src/services/agreementActivationProcessor.ts
packages/agreement-process/src/services/agreementService.ts
packages/agreement-process/src/services/agreementStampUtils.ts
packages/agreement-process/test/activateAgreement.test.ts

Bug found while implementing tests for incaricato in #1277 (feature Capofila).
The delegationId parameter was not passed to the function that adds/removes the `suspendedByProducer` stamp on activation or suspension, meaning that in case the caller is the delegate producer, the `suspendedByProducer`  stamp is not added on suspension or removed on activation.

Added missing delegation param to agreement activation

---

collections/bff/delegation/consumer/Approve Consumer Delegation.bru
collections/bff/delegation/consumer/Create Consumer Delegation.bru
collections/bff/delegation/consumer/Reject Consumer Delegation.bru
collections/bff/delegation/consumer/Revoke Consumer Delegation.bru
collections/bff/delegation/producer/Approve Producer Delegation.bru
collections/bff/delegation/producer/Create Producer Delegation.bru
collections/bff/delegation/producer/Reject Producer Delegation.bru
collections/bff/delegation/producer/Revoke Producer Delegation.bru
packages/api-clients/open-api/bffApi.yml
packages/backend-for-frontend/src/routers/consumerDelegationRouter.ts
packages/backend-for-frontend/src/routers/delegationRouter.ts
packages/backend-for-frontend/src/routers/producerDelegationRouter.ts
packages/backend-for-frontend/src/services/delegationService.ts

- Fixing some naming in Bruno calls and adding vars on creation to simplify local testing
- Removing delegate/delegator prefixes from delegationService.ts calls in BFF to align to the naming in delegation-process and the operationId fields in the bff API spec. Also, these prefixes were misleading, in my opinion: if we have `delegateRejectConsumerDelegation,` it seems that we could also have some other reject that is not for the delegate, while it's actually only the delegate that can reject (the same goes for other methods; only one of the tenants can perform them, either the delegate or the delegator).

Minor fixes on BFF delegations

---

packages/tenant-process/src/services/tenantService.ts
packages/tenant-process/src/services/validators.ts
packages/tenant-process/test/revokeVerifiedAttribute.test.ts
packages/tenant-process/test/verifyVerifiedAttribute.test.ts

This PR changes verification and revocation services logic allowing [this](https://pagopa.atlassian.net/wiki/spaces/PDNDI/pages/1183186970/SRS+Capofila#Edge-case) edge case, as descripted in the SRS.
Plus fixes a bug where, in case the requester was a delegate, the revoker/verifier id assigned to the `revokedBy`/`verifiedBy`, was the delegate's one.

Allow delegate attribute self verification

---

packages/backend-for-frontend/src/services/catalogService.ts

In this PR has been updated a bit of logic for 'enhanceCatalogEService' method trying to restrict API calls to tenant-service when method had called it before.

PIN-5500: added 'caching" tenant  within enhanceCatalogEService method

---

packages/agreement-platformstate-writer/src/consumerServiceV1.ts
packages/agreement-platformstate-writer/src/consumerServiceV2.ts
packages/agreement-platformstate-writer/src/utils.ts
packages/agreement-platformstate-writer/test/consumerServiceV1.integration.test.ts
packages/agreement-platformstate-writer/test/consumerServiceV2.integration.test.ts
packages/agreement-platformstate-writer/test/utils.test.ts

Removed `platform-states` delete function from `agreement-platformstate-writer` and changed the logic to set agreement state to inactive when archiving.

Remove platform-states delete from agreement-platformstate-writer

---

packages/delegation-process/src/services/readModelService.ts

Unused and also shall not exist: we never create objects in our readmodel services.

Removing unused method in delegation process

---

packages/api-clients/src/bffApi.ts
packages/backend-for-frontend/src/services/delegationService.ts
packages/delegation-process/src/model/domain/errors.ts
packages/delegation-process/src/services/delegationService.ts
packages/delegation-process/src/utilities/errorMappers.ts
packages/delegation-process/test/getConsumerDelegators.test.ts
packages/delegation-process/test/getConsumerEservices.test.ts

[Closes: [PIN-6132](https://pagopa.atlassian.net/browse/PIN-6132)]
Refactor the `getConsumerDelegators` function to use a single filter object instead of multiple parameters. Remove the error handling for non-consumer delegates. Update related tests accordingly.
This endpoint shouldn't throw error but instead return an empty array
[PIN-6132]: https://pagopa.atlassian.net/browse/PIN-6132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PIN-6132]: Remove error handling from getConsumerDelegators

---

packages/authorization-server/src/services/tokenService.ts
packages/backend-for-frontend/src/services/toolService.ts
packages/client-assertion-validation/src/validation.ts
packages/client-assertion-validation/test/validation.test.ts
packages/models/src/client-assertion/clientAssertionValidation.ts

This PR removes the strictness on client assertion claims checks.
Before this change, the validation blocked a client assertion containing claims unexpected and not listed in the documentation.
With this PR, any additional claim is ignored, but logged

PIN-6157: Auth server - Allow unknown claims in client assertion

---

packages/api-clients/open-api/apiGatewayApi.yml
packages/api-gateway/src/services/readModelService.ts

The zod typecheck failure was due to the missing `clientId` in the `apiGateway.JWK` model
Previously, this issue did not surface because Zod’s passthrough mode allowed the presence of unexpected properties without strict validation. However, https://github.com/pagopa/interop-be-monorepo/pull/1350 enforces strict type checking on all API models, making the error happen

Fix `getJWK` api-gateway 500 error

---

.github/workflows/pr.yml
packages/api-clients/open-api/bffApi.yml
packages/backend-for-frontend/src/api/tenantApiConverter.ts
packages/backend-for-frontend/src/services/catalogService.ts

This PR add information needed by front-end applications:
- `TenantKind`for organization (route: `/tenants/:TenantId`)
-  `DeprecatedAt, PublishedAt` (route: `/eservices/:eserviceId/descriptors/:descriptorId`)

PIN-6164: Added new Fields for some BFF route

---

packages/tenant-process/src/routers/TenantRouter.ts

I simply removed the _API_ROLE_ role from the roles allowed to call the following two APIs:
- POST /tenants/:tenantId/mails
- DELETE /tenants/:tenantId/mails/:mailId
Link to Jira: https://pagopa.atlassian.net/browse/PIN-5105

Pin 5105 bke in add tenant mail bisogna rimuovere l autorizzazione ad api

---

packages/api-clients/open-api/bffApi.yml
packages/api-clients/open-api/eserviceTemplateApi.yml
packages/backend-for-frontend/src/routers/eserviceTemplateRouter.ts
packages/backend-for-frontend/src/services/eserviceTemplateService.ts
packages/eservice-template-instances-updater/src/eserviceTemplateInstancesUpdaterConsumerServiceV2.ts
packages/eservice-template-instances-updater/test/eserviceTemplateInstancesUpdaterConsumerServiceV2.test.ts
packages/eservice-template-process/src/model/domain/toEvent.ts
packages/eservice-template-process/src/routers/EServiceTemplateRouter.ts
packages/eservice-template-process/src/services/eserviceTemplateService.ts
packages/eservice-template-process/src/utilities/errorMappers.ts
packages/eservice-template-process/test/updateEServiceTemplateIntendedTarget.test.ts
packages/eservice-template-readmodel-writer/src/consumerServiceV2.ts
packages/models/proto/v2/eservice-template/events.proto
packages/models/src/eservice-template/eserviceTemplateEvents.ts

Fix missing `Template` in everything related to the `IntentedTarget` data

Renamed `EServiceIntendedTarget` to `EServiceTemplateIntendedTarget`

---

collections/eservice-template/Update EService Template  Intended Target.bru
packages/api-clients/open-api/bffApi.yml
packages/api-clients/open-api/catalogApi.yml
packages/api-clients/open-api/eserviceTemplateApi.yml
packages/backend-for-frontend/src/api/eserviceTemplateApiConverter.ts
packages/backend-for-frontend/src/routers/eserviceTemplateRouter.ts
packages/backend-for-frontend/src/services/eserviceTemplateService.ts
packages/catalog-process/src/routers/EServiceRouter.ts
packages/eservice-template-process/src/routers/EServiceTemplateRouter.ts
packages/eservice-template-process/src/services/eserviceTemplateService.ts

- Fix Parsing error in ProducerEServiceTemplate.
- Update intended target service payload. Replaced incorrect "description" field with "intendedTarget".
- Fix calling wrong `eserviceTemplateService` in delete e-service template version route
- Fix wrong parameter order (offset/limit) in get e-service creators call
- Removed format uuid `instanceLabel` from api
- Fix missing `send` on res status 204

Fix e-service templates [Part 2]

---

packages/api-clients/open-api/bffApi.yml
packages/backend-for-frontend/src/api/catalogApiConverter.ts
packages/catalog-process/src/services/catalogService.ts

This PR fixes a bug where `templateVersionRef` go missing when the user tries to upload an e-service template

Fix missing `templateVersionRef` after interface upload in e-service template instance

---

collections/bff/authorization/get Session Token.bru
docker/local-kms-seed/jwks.json
packages/agreement-process/.env
packages/anac-certified-attributes-importer/.env
packages/api-gateway/.env
packages/attribute-registry-process/.env
packages/authorization-process/.env
packages/authorization-updater/.env
packages/backend-for-frontend/.env
packages/catalog-process/.env
packages/client-purpose-updater/.env
packages/commons-test/test/jwt.unit.test.ts
packages/compute-agreements-consumer/.env
packages/delegation-items-archiver/.env
packages/delegation-process/.env
packages/eservice-descriptors-archiver/.env
packages/eservice-template-instances-updater/.env
packages/eservice-template-process/.env
packages/ipa-certified-attributes-importer/.env
packages/ivass-certified-attributes-importer/.env
packages/purpose-process/.env
packages/selfcare-onboarding-consumer/.env
packages/tenant-process/.env

#1660 removed the discontinued dev key. Still, it also removed from the well-known local [key used by the local KMS instance](https://vscode.dev/github/pagopa/interop-be-monorepo/blob/develop/docker/local-kms-seed/seed.yaml#L6) to generate internal tokens for local development.
This PR:
- re-adds that key
- fixes kids, audiences, subjects, and issuers all around the codebase local env vars
Tested locally, I can successfully generate a local internal token and use it to call one of the services 👇

Re-adding local KMS key to local well-known

---

packages/backend-for-frontend/src/services/authorizationService.ts

**Jira Link**: https://pagopa.atlassian.net/browse/PIN-6468
I removed the duplicate call to tenant-process because I verified that the data returned by both was the same, and the tenant properties used by other functions within the BFF service did not have different values between the two services.

Removed double call from bff to tenant-process getTenant service

---

packages/dtd-catalog-exporter/src/services/dtdCatalogExporterService.ts
packages/dtd-catalog-exporter/src/services/github-client.services.ts

This PR should fix the error thrown by Octokit not being recognized as a `RequestError` and, as such, not returning undefined for non existing files.
The error object has a different structure, so this should now be caught correctly.
Here's an example of the error:
```
{
"response": {
"url": "https://api.github.com/repos/italia/pdnd-opendata/contents/data%2Fcatalogo_eservice.json",
"status": 404,
"headers": {
"access-control-allow-origin": "*",
"access-control-expose-headers": "ETag,Link,Location,Retry-After,X-GitHub-OTP,X-RateLimit-Limit,X-RateLimit-Remaining,X-RateLimit-Used,X-RateLimit-Resource,X-RateLimit-Reset,X-OAuth-Scopes,X-Accepted-OAuth-Scopes,X-Poll-Interval,X-GitHub-Media-Typ",
"content-encoding": "gzip",
"content-security-policy": "default-src'none'",
"content-type": …
```

Fix dtd export request error

---

packages/agreement-outbound-writer/package.json
packages/catalog-outbound-writer/package.json
packages/catalog-outbound-writer/src/converters/toOutboundEventV2.ts
packages/delegation-outbound-writer/package.json
packages/eservice-template-outbound-writer/package.json
packages/purpose-outbound-writer/package.json
packages/tenant-outbound-writer/package.json
pnpm-lock.yaml

This PR bump the outbound models version to `1.5.4` and adds support for template related events to `catalog-outbound-writer`

Bumped outbound models and updated catalog outbound writer

---

renovate.json

Renovate is having problems opening PRs due to automerge.
Temporarily disabling the feature

fix: Disable Renovate automerge

---

packages/api-clients/open-api/bffApi.yml
packages/backend-for-frontend/src/services/catalogService.ts

As requester by the frontend, the `delegation` information has been inserted inside the `ProducerEServiceDetails`.
This solves two bugs in the frontend.

PIN-6479 - Add delegation in producer e-service details bff model

---

packages/backend-for-frontend/src/routers/catalogRouter.ts
packages/backend-for-frontend/src/services/catalogService.ts
packages/backend-for-frontend/src/utilities/errorMappers.ts

This PR solves a zod parsing error for bff's `EServiceDoc` data in the update document call.

Fix bff update e-service document 500 error

---

packages/authorization-process/src/utilities/errorMappers.ts

Introduce a new mapping for the "organizationNotAllowedOnClient" error to return a forbidden status code.

PIN-6700: Add organizationNotAllowedOnClient in getClient

---

collections/attribute/Create certified attribute.bru
collections/m2m gateway/certifiedAttributes/Get certified attribute.bru
collections/m2m gateway/certifiedAttributes/folder.bru
packages/attribute-registry-process/src/routers/AttributeRouter.ts
packages/attribute-registry-process/test/api/getAttributeById.test.ts
packages/m2m-gateway/package.json
packages/m2m-gateway/src/api/attributeApiConverter.ts
packages/m2m-gateway/src/model/errors.ts
packages/m2m-gateway/src/routers/attributeRouter.ts
packages/m2m-gateway/src/services/attributeService.ts
packages/m2m-gateway/src/utils/errorMappers.ts
packages/m2m-gateway/src/utils/validators/attributeValidators.ts
packages/m2m-gateway/test/.eslintrc.json
packages/m2m-gateway/test/api/certifiedAttributes/getCertifiedAttribute.test.ts
packages/m2m-gateway/test/integration/certifiedAttributes/getCertifiedAttribute.test.ts
packages/m2m-gateway/test/integrationUtils.ts
packages/m2m-gateway/test/mockUtils.ts
packages/m2m-gateway/test/vitest.api.setup.ts
pnpm-lock.yaml

Closes [PIN-6772](https://pagopa.atlassian.net/browse/PIN-6772)
GET `/certifiedAttributes/:attributeId`
Checklist:
[PIN-6772]: https://pagopa.atlassian.net/browse/PIN-6772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN-6772 - M2M - GET certified attribute by ID

---

packages/commons/package.json
packages/commons/src/logging/index.ts
pnpm-lock.yaml

Closes [PIN-6856](https://pagopa.atlassian.net/browse/PIN-6856)
This PR is to set winston's `forceConsole` to true. It should fix the problem we have on CloudWatch where multiline messages are separated on multiple logs.
I didn't update winston to v3.17.0 because it currently [gives type problems](https://github.com/winstonjs/logform/issues/336).
[PIN-6856]: https://pagopa.atlassian.net/browse/PIN-6856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIN-6856 - Update `winston` to 3.16.0 and use `forceConsole`

---

packages/backend-for-frontend/src/app.ts

This PR fixes the position of the `authorization router`, which should not be placed after the token validation

Fix bff router

---

packages/catalog-platformstate-writer/src/consumerServiceV2.ts
packages/catalog-platformstate-writer/test/consumerServiceV2.test.ts

This PR fixes the handler for `EServiceDescriptorQuotasUpdatedByTemplateUpdate`: this event should update the descriptor quotas in the `token-generation-readmodel` as well.

Fix EServiceDescriptorQuotasUpdatedByTemplateUpdate in catalog-platformstate-writer

---

packages/authorization-process/src/services/readModelServiceSQL.ts
packages/notification-email-sender/src/services/notificationEmailSenderService.ts
packages/notification-email-sender/test/sendNewPurposeVersionWaitingForApprovalEmail.integration.test.ts
packages/notification-email-sender/test/sendPurposeWaitingForApprovalEmail.integration.test.ts

Update the email sender service to utilize the producer's email instead of the consumer's email on purpose events, ensuring that notifications are sent to the correct recipient. Adjust related tests to reflect this change.

PIN-6974: fix for notification-email-sender purpose mails (Including a small improvement on a query)

---

packages/selfcare-client-users-updater/src/model/UsersEventPayload.ts
packages/selfcare-client-users-updater/test/selfcareClientUsersUpdaterProcessor.test.ts

Since we received a new event with relationshipStatus `REJECTED`, which wasn't supported by the model and we actually only check for `ACTIVE`, the relationshipStatus enum is replaced by `z.string()` while keeping the enum for comparison purposes

replace RelationshipStatus enum with string in UsersEventPayload

---

packages/commons-test/src/testUtils.ts
packages/dpop-validation/package.json
packages/dpop-validation/src/errors.ts
packages/dpop-validation/src/utilities/utils.ts
packages/dpop-validation/src/validation.ts
packages/dpop-validation/test/validation.test.ts
packages/models/src/authorization/key.ts
pnpm-lock.yaml

This PR fixes the DPoP Proof header's JWK which is not supposed to have the claims `alg`, `use` and `kid`.

Fix JWK in DPoP Proof header

---

docker/domains-analytics-db/domains-init.sql
packages/domains-analytics-writer/src/handlers/authorization/consumerServiceV2.ts
packages/domains-analytics-writer/src/index.ts
packages/domains-analytics-writer/src/model/authorization/producerKeychain.ts
packages/domains-analytics-writer/src/model/authorization/producerKeychainEService.ts
packages/domains-analytics-writer/src/model/authorization/producerKeychainKey.ts
packages/domains-analytics-writer/src/model/authorization/producerKeychainUser.ts
packages/domains-analytics-writer/src/model/db/authorization.ts
packages/domains-analytics-writer/src/model/db/deleting.ts
packages/domains-analytics-writer/src/model/db/index.ts
packages/domains-analytics-writer/src/repository/producerKeychain/producerKeychain.repository.ts
packages/domains-analytics-writer/src/repository/producerKeychain/producerKeychainEService.repository.ts
packages/domains-analytics-writer/src/repository/producerKeychain/producerKeychainKey.ts
packages/domains-analytics-writer/src/repository/producerKeychain/producerKeychainUser.repository.ts
packages/domains-analytics-writer/src/service/authorizationService.ts
packages/domains-analytics-writer/test/authorizationService.test.ts
packages/domains-analytics-writer/test/utils.ts

This PR introduces:
-  `handleAuthorizationMessageV2` functions to handle `ProducerKeychain events `from the `authorization` topic
**Hybrid delete strategy**  
- The `ProducerKeychainDeleted` events performs a **logical delete** on the main `producer_keychain` table  and its subobjects (sets the `deleted` flag, preserving history to the target tables).  
- All other delete events execute **physical deletes**, removing rows outright from target tables.
**Pre-merge cleanup**  
Before each upsert MERGE, we now run a set-based `MERGE … WHEN MATCHED THEN DELETE` on the target tables to purge any rows whose `metadata_version` is lower than the incoming staging version, ensuring outdated records will be cleaned.

PIN-7015: Analytics - Authorization producerKeychain (implementation) 

---

packages/catalog-platformstate-writer/src/consumerServiceV1.ts
packages/catalog-platformstate-writer/src/consumerServiceV2.ts
packages/catalog-platformstate-writer/src/utils.ts
packages/catalog-platformstate-writer/test/consumerServiceV1.test.ts
packages/catalog-platformstate-writer/test/consumerServiceV2.test.ts
packages/catalog-platformstate-writer/test/utils.test.ts
packages/purpose-platformstate-writer/src/consumerServiceV1.ts
packages/purpose-platformstate-writer/src/consumerServiceV2.ts
packages/purpose-platformstate-writer/src/utils.ts
packages/purpose-platformstate-writer/test/consumerServiceV1.integration.test.ts
packages/purpose-platformstate-writer/test/consumerServiceV2.integration.test.ts
packages/purpose-platformstate-writer/test/utils.test.ts

The events that write an entry should overwrite it if it already exists in the `platform-states` table because this action is needed for the events reprocessing.

Fix `catalog-platformstate-writer` and `purpose-platformstate-writer` reprocess

---

packages/api-clients/open-api/catalogApi.yml
packages/api-clients/open-api/eserviceTemplateApi.yml
packages/api-clients/open-api/m2mGatewayApi.yml
packages/api-clients/open-api/purposeApi.yml
packages/commons/src/risk-analysis/rules/PA/2.0.ts
packages/commons/src/risk-analysis/rules/PA/3.0.ts
packages/commons/src/risk-analysis/rules/PRIVATE/1.0.ts
packages/commons/src/risk-analysis/rules/PRIVATE/2.0.ts
packages/commons/src/risk-analysis/rules/riskAnalysisFormRules.ts
packages/purpose-process/src/model/domain/apiConverter.ts

Related PR #1962 
This PR:
- increases the risk analysis answers max length to `2000`;
- adds the `validation` property to the `formConfigQuestionToApiFormConfigQuestion` function because it's needed by the FE.
Tested locally on the endpoint `/backend-for-frontend/purposes/riskAnalysis/latest?tenantKind={tenantKind}` which now also returns `validation` for the `"dataType": "FREETEXT"` questions.

PIN-7185 - Fix risk analysis answers length by increasing the max length to 2000

---

collections/m2m gateway/purposes/Download Purpose version Risk Analysis document.bru
packages/api-clients/open-api/m2mGatewayApi.yml
packages/m2m-gateway/src/routers/purposeRouter.ts
packages/m2m-gateway/src/services/purposeService.ts
packages/m2m-gateway/src/utils/errorMappers.ts
packages/m2m-gateway/test/api/purposes/downloadPurposeVersionRiskAnalysisDocument.test.ts
packages/m2m-gateway/test/integration/purposes/downloadPurposeVersionRiskAnalysisDocument.test.ts

This PR renames the path of the service that downloads purpose risk analysis document
from: `/purposes/{purposeId}/versions/{versionId}/document`
to: `/purposes/{purposeId}/versions/{versionId}/riskAnalysisDocument`
Also renamed all the services/files related accordingly

PIN-7195 - Renamed M2M Api download purpose document

---

collections/agreement/Create Agreement.bru
collections/catalog/Create Eservice.bru
collections/environments/PagoPA local.bru
collections/m2m gateway/purposes/Create Reverse Purpose.bru
collections/m2m gateway/purposes/Create purpose.bru
packages/api-clients/open-api/m2mGatewayApi.yml
packages/api-clients/open-api/purposeApi.yml
packages/m2m-gateway/src/model/errors.ts
packages/m2m-gateway/src/routers/purposeRouter.ts
packages/m2m-gateway/src/services/purposeService.ts
packages/m2m-gateway/src/utils/errorMappers.ts
packages/m2m-gateway/src/utils/validators/validators.ts
packages/m2m-gateway/test/api/purposes/createPurpose.test.ts
packages/m2m-gateway/test/api/purposes/createReversePurpose.test.ts
packages/m2m-gateway/test/integration/purposes/createPurpose.test.ts
packages/m2m-gateway/test/integration/purposes/createReversePurpose.test.ts

[PIN-7354](https://pagopa.atlassian.net/browse/PIN-7354)
Purpose creation in the purpose process requires a consumerId ID, which can be set to:
1. the caller tenant or
2. a tenant for whom the caller is the consumer delegate
This consumerId param is also required via M2M for reverse purpose creation.
However, for normal purpose creation, we decided to expose `delegationId` to create a purpose as the consumer delegate. The parameter is just passed down to the process call, causing a Bad Request, and the consumerId is always set to the caller, preventing the creation of a delegated purpose via M2M.
**Solution:**
We want to expose delegationId in both calls, and in case it's set we pass down the delegator as consumerId to the purpose process.
The call to the process was sending back a 400 …

PIN-7354 fixing delegated purpose creation in API V2

---

packages/api-gateway/src/services/purposeService.ts

This PR adds the error 403 mapping to the `retrievePurpose` function in the `api-gateway`.
BEFORE
AFTER

PIN-7436 - Add error 403 mapping to `retrievePurpose` in `api-gateway`

---

packages/commons/src/risk-analysis-template/riskAnalysisTemplateValidation.ts
packages/readmodel/src/purposeTemplateReadModelService.ts

- Improve risk analysis validations functions readability 
- Remove useless `and` operator from query provided in `packages/readmodel/src/purposeTemplateReadModelService.ts`

Purpose template splitter aggregator refactor validation

---

packages/catalog-process/src/routers/EServiceRouter.ts
packages/catalog-process/src/services/catalogService.ts
packages/catalog-process/test/api/updateDescriptorAttributes.test.ts

This PR allows `API_ROLE` and `M2M_ADMIN_ROLE` to update attributes of a descriptor after publication.

hotfix: PIN-7773 Allow api user to edit attributes of published descriptor

---

packages/agreement-lifecycle/AUTHORS
packages/agreement-lifecycle/LICENSE
packages/agreement-lifecycle/package.json

Hi, this PR:
* adds the correct structure for licensing the single packages, which means having the MPL-2.0 `LICENSE` + the appropriate `AUTHORS` file and fixing the corresponding entries in the `package.json` file. 
Please note that we are **not** explicitly mentioning the authors or the contributors in the package.json but we are generically referring to the package's root `AUTHORS` file.  
This is just a template example for the first package, the same structure should be kept also in **all** the other packages as discussed. 
LMK if you need further details, thanks

Add `agreement-lifecycle` package license

---

packages/purpose-template-process/src/model/domain/errors.ts
packages/purpose-template-process/src/services/validators.ts

- [PIN-7841](https://pagopa.atlassian.net/browse/PIN-7841)
This PR adds the common validators and errors to the `purpose-template-process`. This is to not re-write the same code in different PRs.
- purpose-template-process
[PIN-7841]: https://pagopa.atlassian.net/browse/PIN-7841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature: add common purpose-template-process validators and errors (PIN-7841)
